import { OperationCode } from "./typesPseudoCode";

export const getArbolSplayCode = (): Record<string, OperationCode> => ({
    insert: {
        lines: [
            `/**
 * Método que inserta un nuevo elemento en el árbol Splay.
 * - Si el elemento ya existe: se aplica splay del nodo encontrado para moverlo a la raíz.
 * - Si no existe: se inserta como BST y luego se aplica splay del nuevo nodo para moverlo a la raíz. 
 * 
 * @param valor Elemento a insertar o acceder.
 * @return true si el elemento fue insertado, false si ya existía.
 */`,
            `public boolean insertar(T {0}) {`,
            `    NodoSplay<T> p = null;`,
            `    NodoSplay<T> cur = this.raiz;`,
            `    while (cur != null) {`,
            `        int cmp = {0}.compareTo(cur.info);`,
            `        if (cmp == 0) {`,
            `            this.splay(cur);`,
            `            return false;`,
            `        }`,
            `        p = cur;`,
            `        cur = cmp < 0 ? cur.izquierdo : cur.derecho;`,
            `    }`,
            `    NodoSplay<T> x = new NodoSplay<>({0});`,
            `    x.padre = p;`,
            `    if (p == null) {`,
            `        this.raiz = x;`,
            `    } else if (x.info.compareTo(p.info) < 0) {`,
            `        p.izquierdo = x;`,
            `    } else {`,
            `        p.derecho = x;`,
            `    }`,
            `    this.splay(x);`,
            `    {1}++`,
            `    return true;`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza la operación de splay sobre el nodo dado, moviéndolo hasta la raíz
 * mediante rotaciones Zig, Zig-Zig o Zig-Zag según corresponda:
 * 
 * 1. Zig: Nodo es hijo directo de la raíz -> una rotación.
 * 2. Zig-Zig: Nodo y padre son ambos hijos izquierdos o derechos -> dos rotaciones en la misma dirección.
 * 3. Zig-Zag: Nodo y padre están en direcciones opuestas -> dos rotaciones en direcciones distintas.
 * 
 * @param x Nodo a splayear hasta la raíz.
 */`,
            `private void splay(NodoSplay<T> x) {`,
            `    while (x.padre != null) {`,
            `        NodoSplay<T> p = x.padre;`,
            `        NodoSplay<T> g = p.padre;`,
            `\n`,
            `        if (g == null) {`,
            `            // Zig`,
            `            if (x == p.izquierdo) {`,
            `                this.rotacionDerecha(p);`,
            `            } else {`,
            `                this.rotacionIzquierda(p);`,
            `            }`,
            `        } else {`,
            `            boolean xEsIzq = x == p.izquierdo;`,
            `            boolean pEsIzq = p == g.izquierdo;`,
            `\n`,
            `            if (xEsIzq && pEsIzq) {`,
            `                // Zig-Zig LL`,
            `                this.rotacionDerecha(g);`,
            `                this.rotacionDerecha(p);`,
            `            } else if (!xEsIzq && !pEsIzq) {`,
            `                // Zig-Zig RR`,
            `                this.rotacionIzquierda(g);`,
            `                this.rotacionIzquierda(p);`,
            `            } else if (!xEsIzq && pEsIzq) {`,
            `                // Zig-Zag LR`,
            `                this.rotacionIzquierda(p);`,
            `                this.rotacionDerecha(g);`,
            `            } else {`,
            `                // Zig-Zag RL`,
            `                this.rotacionDerecha(p);`,
            `                this.rotacionIzquierda(g);`,
            `            }`,
            `        }`,
            `    }`,
            `    this.raiz = x;`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza una rotación simple a la derecha en el subárbol dado.
 * @param y Nodo raíz del subárbol a rotar.
 */`,
            `private void rotacionDerecha(NodoSplay<T> y) {`,
            `    NodoSplay<T> x = y.izquierdo;`,
            `    NodoSplay<T> T2 = x.derecho;`,
            `\n`,
            `    x.padre = y.padre;`,
            `    if (y.padre == null) {`,
            `        this.raiz = x;`,
            `    } else if (y == y.padre.derecho) {`,
            `        y.padre.derecho = x;`,
            `    } else {`,
            `        y.padre.izquierdo = x;`,
            `    }`,
            `\n`,
            `    x.derecho = y;`,
            `    y.padre = x;`,
            `\n`,
            `    y.izquierdo = T2;`,
            `    if (T2 != null) {`,
            `        T2.padre = y;`,
            `    }`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza una rotación simple a la izquierda en el subárbol dado.
 * @param x Nodo raíz del subárbol a rotar.
 */`,
            `private void rotacionIzquierda(NodoSplay<T> x) {`,
            `    NodoSplay<T> y = x.derecho;`,
            `    NodoSplay<T> T2 = y.izquierdo;`,
            `\n`,
            `    y.padre = x.padre;`,
            `    if (x.padre == null) {`,
            `        this.raiz = y;`,
            `    } else if (x == x.padre.izquierdo) {`,
            `        x.padre.izquierdo = y;`,
            `    } else {`,
            `        x.padre.derecho = y;`,
            `    }`,
            `\n`,
            `    y.izquierdo = x;`,
            `    x.padre = y;`,
            `\n`,
            `    x.derecho = T2;`,
            `    if (T2 != null) {`,
            `        T2.padre = x;`,
            `    }`,
            `}`,
        ],
        labels: {
            DECLARE_PARENT: 2,
            DECLARE_CURSOR: 3,
            BST_WHILE: 4,
            DECLARE_CMP: 5,
            IF_DUPLICATE: 6,
            SPLAY_EXISTING: 7,
            RETURN_FALSE: 8,
            SET_PARENT: 10,
            ADVANCE_CURSOR: 11,
            CREATE_NODE: 13,
            SET_NODE_PARENT: 14,
            IF_P_NULL: 15,
            SET_ROOT: 16,
            ELSE_IF_ATTACH_LEFT: 17,
            ATTACH_NODE_LEFT: 18,
            ELSE_ATTACH_RIGHT: 19,
            ATTACH_NODE_RIGHT: 20,
            SPLAY_NEW: 22,
            INC_SIZE: 23,
            RETURN_TRUE: 24,

            // splay(NodoSplay<T> x)
            SPLAY_WHILE: 30,
            SPLAY_DECLARE_P: 31,
            SPLAY_DECLARE_G: 32,
            IF_G_NULL: 34,
            IF_X_LEFT_ZIG: 36,
            ZIG_ROTATE_RIGHT_P: 37,
            ELSE_X_RIGHT_ZIG: 38,
            ZIG_ROTATE_LEFT_P: 39,
            ELSE_G_NOT_NULL: 41,
            DECL_X_IS_LEFT: 42,
            DECL_P_IS_LEFT: 43,
            IF_ZIGZIG_LL: 45,
            ZIGZIG_LL_ROT1: 47,
            ZIGZIG_LL_ROT2: 48,
            ELSE_IF_ZIGZIG_RR: 49,
            ZIGZIG_RR_ROT1: 51,
            ZIGZIG_RR_ROT2: 52,
            ELSE_IF_ZIGZAG_LR: 53,
            ZIGZAG_LR_ROT1: 55,
            ZIGZAG_LR_ROT2: 56,
            ELSE_ZIGZAG_RL: 57,
            ZIGZAG_RL_ROT1: 59,
            ZIGZAG_RL_ROT2: 60,
            SET_ROOT_END: 64,

            // rotacionDerecha(NodoSplay<T> y)
            ROT_R_DECL_X: 70,
            ROT_R_DECL_T2: 71,
            ROT_R_SET_X_PARENT: 73,
            ROT_R_IF_Y_PARENT_NULL: 74,
            ROT_R_SET_ROOT: 75,
            ROT_R_ELSE_IF_Y_IS_RIGHT: 76,
            ROT_R_SET_PARENT_RIGHT: 77,
            ROT_R_ELSE_Y_IS_LEFT: 78,
            ROT_R_SET_PARENT_LEFT: 79,
            ROT_R_SET_X_RIGHT: 82,
            ROT_R_SET_Y_PARENT: 83,
            ROT_R_SET_Y_LEFT: 85,
            ROT_R_IF_T2_NOT_NULL: 86,
            ROT_R_SET_T2_PARENT: 87,

            // rotacionIzquierda(NodoSplay<T> x)
            ROT_L_DECL_Y: 94,
            ROT_L_DECL_T2: 95,
            ROT_L_SET_Y_PARENT: 97,
            ROT_L_IF_X_PARENT_NULL: 98,
            ROT_L_SET_ROOT: 99,
            ROT_L_ELSE_IF_X_IS_LEFT: 100,
            ROT_L_SET_PARENT_LEFT: 101,
            ROT_L_ELSE_X_IS_RIGHT: 102,
            ROT_L_SET_PARENT_RIGHT: 103,
            ROT_L_SET_Y_LEFT: 106,
            ROT_L_SET_X_PARENT: 107,
            ROT_L_SET_X_RIGHT: 109,
            ROT_L_IF_T2_NOT_NULL: 110,
            ROT_L_SET_T2_PARENT: 111
        }
    },
    delete: {
        lines: [
            `/**
 * Método que elimina el elemento especificado del árbol Splay.
 * - Si el elemento existe: se aplica splay del nodo encontrado para moverlo a la raíz antes de ser eliminado.
 * - Si no existe: se aplica splay del último nodo visitado durante la búsqueda para moverlo a la raíz y no se elimina nada. 
 * 
 * @param valor Elemento a eliminar.
 * @return true si el elemento fue eliminado, false si no existe en el árbol.
 * @throws RuntimeException si el árbol está vacío.
 */`,
            `public boolean delete(T {0}) {`,
            `    if (this.raiz == null) {`,
            `        throw new RuntimeException("No fue posible eliminar el nodo: El árbol se encuentra vacío (cantidad de nodos: 0).");`,
            `    }`,
            `    boolean esta = this.search({0});`,
            `    if (!esta) {`,
            `        return false;`,
            `    }`,
            `\n`,
            `    NodoSplay<T> root = this.raiz;`,
            `    NodoSplay<T> subIzq = root.izquierdo;`,
            `    NodoSplay<T> subDer = root.derecho;`,
            `    if (subIzq != null) {`,
            `        subIzq.padre = null;`,
            `    }`,
            `    if (subDer != null) {`,
            `        subDer.padre = null;`,
            `    }`,
            `    root.derecho = null;`,
            `    root.izquierdo = null;`,
            `    this.raiz = null;`,
            `\n`,
            `    if (subIzq == null) {`,
            `        this.raiz = subDer;`,
            `        {1}--;`,
            `        return true;`,
            `    }`,
            `    this.raiz = subIzq;`,
            `    NodoSplay<T> maxIzq = this.raiz;`,
            `    while (maxIzq.derecho != null) {`,
            `           maxIzq = maxIzq.derecho;`,
            `    }`,
            `    this.splay(maxIzq);`,
            `    this.raiz.derecho = subDer;`,
            `    if (subDer != null) {`,
            `        subDer.padre = this.raiz;`,
            `    }`,
            `    {1}--;`,
            `    return true;`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método que comprueba la existencia del elemento especificado en el árbol Splay.
 * - Si el elemento existe: se aplica splay del nodo encontrado para moverlo a la raíz.
 * - Si no existe: se aplica splay del último nodo visitado durante la búsqueda para moverlo a la raíz.
 * 
 * @param info Elemento a buscar.
 * @return true si el elemento existe en el árbol, false en caso contrario.
 */`,
            `public boolean search(T {0}) {`,
            `    NodoSplay<T> curr = this.raiz;`,
            `    NodoSplay<T> ultimo = null;`,
            `    while (curr != null) {`,
            `        ultimo = curr;`,
            `        int cmp = {0}.compareTo(curr.info);`,
            `        if (cmp == 0) {`,
            `            this.splay(curr);`,
            `            return true;`,
            `        }`,
            `        curr = cmp < 0 ? curr.izquierdo : curr.derecho;`,
            `    }`,
            `    this.splay(ultimo);`,
            `    return false;`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza la operación de splay sobre el nodo dado, moviéndolo hasta la raíz
 * mediante rotaciones Zig, Zig-Zig o Zig-Zag según corresponda:
 * 
 * 1. Zig: Nodo es hijo directo de la raíz -> una rotación.
 * 2. Zig-Zig: Nodo y padre son ambos hijos izquierdos o derechos -> dos rotaciones en la misma dirección.
 * 3. Zig-Zag: Nodo y padre están en direcciones opuestas -> dos rotaciones en direcciones distintas.
 * 
 * @param x Nodo a splayear hasta la raíz.
 */`,
            `private void splay(NodoSplay<T> x) {`,
            `    while (x.padre != null) {`,
            `        NodoSplay<T> p = x.padre;`,
            `        NodoSplay<T> g = p.padre;`,
            `\n`,
            `        if (g == null) {`,
            `            // Zig`,
            `            if (x == p.izquierdo) {`,
            `                this.rotacionDerecha(p);`,
            `            } else {`,
            `                this.rotacionIzquierda(p);`,
            `            }`,
            `        } else {`,
            `            boolean xEsIzq = x == p.izquierdo;`,
            `            boolean pEsIzq = p == g.izquierdo;`,
            `\n`,
            `            if (xEsIzq && pEsIzq) {`,
            `                // Zig-Zig LL`,
            `                this.rotacionDerecha(g);`,
            `                this.rotacionDerecha(p);`,
            `            } else if (!xEsIzq && !pEsIzq) {`,
            `                // Zig-Zig RR`,
            `                this.rotacionIzquierda(g);`,
            `                this.rotacionIzquierda(p);`,
            `            } else if (!xEsIzq && pEsIzq) {`,
            `                // Zig-Zag LR`,
            `                this.rotacionIzquierda(p);`,
            `                this.rotacionDerecha(g);`,
            `            } else {`,
            `                // Zig-Zag RL`,
            `                this.rotacionDerecha(p);`,
            `                this.rotacionIzquierda(g);`,
            `            }`,
            `        }`,
            `    }`,
            `    this.raiz = x;`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza una rotación simple a la derecha en el subárbol dado.
 * @param y Nodo raíz del subárbol a rotar.
 */`,
            `private void rotacionDerecha(NodoSplay<T> y) {`,
            `    NodoSplay<T> x = y.izquierdo;`,
            `    NodoSplay<T> T2 = x.derecho;`,
            `\n`,
            `    x.padre = y.padre;`,
            `    if (y.padre == null) {`,
            `        this.raiz = x;`,
            `    } else if (y == y.padre.derecho) {`,
            `        y.padre.derecho = x;`,
            `    } else {`,
            `        y.padre.izquierdo = x;`,
            `    }`,
            `\n`,
            `    x.derecho = y;`,
            `    y.padre = x;`,
            `\n`,
            `    y.izquierdo = T2;`,
            `    if (T2 != null) {`,
            `        T2.padre = y;`,
            `    }`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza una rotación simple a la izquierda en el subárbol dado.
 * @param x Nodo raíz del subárbol a rotar.
 */`,
            `private void rotacionIzquierda(NodoSplay<T> x) {`,
            `    NodoSplay<T> y = x.derecho;`,
            `    NodoSplay<T> T2 = y.izquierdo;`,
            `\n`,
            `    y.padre = x.padre;`,
            `    if (x.padre == null) {`,
            `        this.raiz = y;`,
            `    } else if (x == x.padre.izquierdo) {`,
            `        x.padre.izquierdo = y;`,
            `    } else {`,
            `        x.padre.derecho = y;`,
            `    }`,
            `\n`,
            `    y.izquierdo = x;`,
            `    x.padre = y;`,
            `\n`,
            `    x.derecho = T2;`,
            `    if (T2 != null) {`,
            `        T2.padre = x;`,
            `    }`,
            `}`,
        ],
        labels: {
            VALIDATE_EMPTY: 2,
            THROW_IF_EMPTY: 3,
            SEARCH_CALL: 5,
            IF_NOT_FOUND: 6,
            RETURN_NOT_FOUND: 7,
            DECLARE_ROOT: 10,
            DECLARE_L_SUB: 11,
            DECLARE_R_SUB: 12,
            IF_L_SUB_IS_NOT_NULL: 13,
            SET_L_SUB_PARENT_NULL: 14,
            IF_R_SUB_IS_NOT_NULL: 16,
            SET_R_SUB_PARENT_NULL: 17,
            SET_ROOT_RIGHT_NULL: 19,
            SET_ROOT_LEFT_NULL: 20,
            SET_ROOT_NULL: 21,
            IF_L_SUB_IS_NULL: 23,
            SET_ROOT_R_SUB: 24,
            DEC_SIZE1: 25,
            RETURN_DELETED1: 26,
            SET_ROOT_L_SUB: 28,
            DECLARE_MAXL: 29,
            MAXL_WHILE: 30,
            SET_MAXL_RIGHT: 31,
            SPLAY_MAXL: 33,
            SET_ROOT_RIGHT_R_SUB: 34,
            IF_R_SUB_IS_NOT_NULL2: 35,
            SET_R_SUB_PARENT_ROOT: 36,
            DEC_SIZE2: 38,
            RETURN_DELETED2: 39,

            // search(T valor)
            DECLARE_CURRENT: 45,
            DECLARE_LAST: 46,
            BST_WHILE: 47,
            SET_LAST_TO_CURR: 48,
            DECLARE_CMP: 49,
            IF_FOUND: 50,
            SPLAY_FOUND: 51,
            RETURN_TRUE: 52,
            ADVANCE_CURRENT: 54,
            SPLAY_LAST: 56,
            RETURN_FALSE: 57,

            // splay(NodoSplay<T> x)
            SPLAY_WHILE: 63,
            SPLAY_DECLARE_P: 64,
            SPLAY_DECLARE_G: 65,
            IF_G_NULL: 67,
            IF_X_LEFT_ZIG: 69,
            ZIG_ROTATE_RIGHT_P: 70,
            ELSE_X_RIGHT_ZIG: 71,
            ZIG_ROTATE_LEFT_P: 72,
            ELSE_G_NOT_NULL: 74,
            DECL_X_IS_LEFT: 75,
            DECL_P_IS_LEFT: 76,
            IF_ZIGZIG_LL: 78,
            ZIGZIG_LL_ROT1: 80,
            ZIGZIG_LL_ROT2: 81,
            ELSE_IF_ZIGZIG_RR: 82,
            ZIGZIG_RR_ROT1: 84,
            ZIGZIG_RR_ROT2: 85,
            ELSE_IF_ZIGZAG_LR: 86,
            ZIGZAG_LR_ROT1: 88,
            ZIGZAG_LR_ROT2: 89,
            ELSE_ZIGZAG_RL: 90,
            ZIGZAG_RL_ROT1: 92,
            ZIGZAG_RL_ROT2: 93,
            SET_ROOT_END: 97,

            // rotacionDerecha(NodoSplay<T> y)
            ROT_R_DECL_X: 103,
            ROT_R_DECL_T2: 104,
            ROT_R_SET_X_PARENT: 106,
            ROT_R_IF_Y_PARENT_NULL: 107,
            ROT_R_SET_ROOT: 108,
            ROT_R_ELSE_IF_Y_IS_RIGHT: 109,
            ROT_R_SET_PARENT_RIGHT: 110,
            ROT_R_ELSE_Y_IS_LEFT: 111,
            ROT_R_SET_PARENT_LEFT: 112,
            ROT_R_SET_X_RIGHT: 115,
            ROT_R_SET_Y_PARENT: 116,
            ROT_R_SET_Y_LEFT: 118,
            ROT_R_IF_T2_NOT_NULL: 119,
            ROT_R_SET_T2_PARENT: 120,

            // rotacionIzquierda(NodoSplay<T> x)
            ROT_L_DECL_Y: 127,
            ROT_L_DECL_T2: 128,
            ROT_L_SET_Y_PARENT: 130,
            ROT_L_IF_X_PARENT_NULL: 131,
            ROT_L_SET_ROOT: 132,
            ROT_L_ELSE_IF_X_IS_LEFT: 133,
            ROT_L_SET_PARENT_LEFT: 134,
            ROT_L_ELSE_X_IS_RIGHT: 135,
            ROT_L_SET_PARENT_RIGHT: 136,
            ROT_L_SET_Y_LEFT: 139,
            ROT_L_SET_X_PARENT: 140,
            ROT_L_SET_X_RIGHT: 142,
            ROT_L_IF_T2_NOT_NULL: 143,
            ROT_L_SET_T2_PARENT: 144
        },
        errorPlans: {
            DELETE_EMPTY: [
                { lineLabel: "VALIDATE_EMPTY", hold: 600 },
                { lineLabel: "THROW_IF_EMPTY", hold: 600 },
            ]
        }
    },
    search: {
        lines: [
            `/**
 * Método que comprueba la existencia del elemento especificado en el árbol Splay.
 * - Si el elemento existe: se aplica splay del nodo encontrado para moverlo a la raíz.
 * - Si no existe: se aplica splay del último nodo visitado durante la búsqueda para moverlo a la raíz.
 * 
 * @param info Elemento a buscar.
 * @return true si el elemento existe en el árbol, false en caso contrario.
 */`,
            `public boolean search(T {0}) {`,
            `    NodoSplay<T> curr = this.raiz;`,
            `    NodoSplay<T> ultimo = null;`,
            `    while (curr != null) {`,
            `        ultimo = curr;`,
            `        int cmp = {0}.compareTo(curr.info);`,
            `        if (cmp == 0) {`,
            `            this.splay(curr);`,
            `            return true;`,
            `        }`,
            `        curr = cmp < 0 ? curr.izquierdo : curr.derecho;`,
            `    }`,
            `    this.splay(ultimo);`,
            `    return false;`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza la operación de splay sobre el nodo dado, moviéndolo hasta la raíz
 * mediante rotaciones Zig, Zig-Zig o Zig-Zag según corresponda:
 * 
 * 1. Zig: Nodo es hijo directo de la raíz -> una rotación.
 * 2. Zig-Zig: Nodo y padre son ambos hijos izquierdos o derechos -> dos rotaciones en la misma dirección.
 * 3. Zig-Zag: Nodo y padre están en direcciones opuestas -> dos rotaciones en direcciones distintas.
 * 
 * @param x Nodo a splayear hasta la raíz.
 */`,
            `private void splay(NodoSplay<T> x) {`,
            `    while (x.padre != null) {`,
            `        NodoSplay<T> p = x.padre;`,
            `        NodoSplay<T> g = p.padre;`,
            `\n`,
            `        if (g == null) {`,
            `            // Zig`,
            `            if (x == p.izquierdo) {`,
            `                this.rotacionDerecha(p);`,
            `            } else {`,
            `                this.rotacionIzquierda(p);`,
            `            }`,
            `        } else {`,
            `            boolean xEsIzq = x == p.izquierdo;`,
            `            boolean pEsIzq = p == g.izquierdo;`,
            `\n`,
            `            if (xEsIzq && pEsIzq) {`,
            `                // Zig-Zig LL`,
            `                this.rotacionDerecha(g);`,
            `                this.rotacionDerecha(p);`,
            `            } else if (!xEsIzq && !pEsIzq) {`,
            `                // Zig-Zig RR`,
            `                this.rotacionIzquierda(g);`,
            `                this.rotacionIzquierda(p);`,
            `            } else if (!xEsIzq && pEsIzq) {`,
            `                // Zig-Zag LR`,
            `                this.rotacionIzquierda(p);`,
            `                this.rotacionDerecha(g);`,
            `            } else {`,
            `                // Zig-Zag RL`,
            `                this.rotacionDerecha(p);`,
            `                this.rotacionIzquierda(g);`,
            `            }`,
            `        }`,
            `    }`,
            `    this.raiz = x;`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza una rotación simple a la derecha en el subárbol dado.
 * @param y Nodo raíz del subárbol a rotar.
 */`,
            `private void rotacionDerecha(NodoSplay<T> y) {`,
            `    NodoSplay<T> x = y.izquierdo;`,
            `    NodoSplay<T> T2 = x.derecho;`,
            `\n`,
            `    x.padre = y.padre;`,
            `    if (y.padre == null) {`,
            `        this.raiz = x;`,
            `    } else if (y == y.padre.derecho) {`,
            `        y.padre.derecho = x;`,
            `    } else {`,
            `        y.padre.izquierdo = x;`,
            `    }`,
            `\n`,
            `    x.derecho = y;`,
            `    y.padre = x;`,
            `\n`,
            `    y.izquierdo = T2;`,
            `    if (T2 != null) {`,
            `        T2.padre = y;`,
            `    }`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza una rotación simple a la izquierda en el subárbol dado.
 * @param x Nodo raíz del subárbol a rotar.
 */`,
            `private void rotacionIzquierda(NodoSplay<T> x) {`,
            `    NodoSplay<T> y = x.derecho;`,
            `    NodoSplay<T> T2 = y.izquierdo;`,
            `\n`,
            `    y.padre = x.padre;`,
            `    if (x.padre == null) {`,
            `        this.raiz = y;`,
            `    } else if (x == x.padre.izquierdo) {`,
            `        x.padre.izquierdo = y;`,
            `    } else {`,
            `        x.padre.derecho = y;`,
            `    }`,
            `\n`,
            `    y.izquierdo = x;`,
            `    x.padre = y;`,
            `\n`,
            `    x.derecho = T2;`,
            `    if (T2 != null) {`,
            `        T2.padre = x;`,
            `    }`,
            `}`,
        ],
        labels: {
            DECLARE_CURRENT: 2,
            DECLARE_LAST: 3,
            BST_WHILE: 4,
            SET_LAST_TO_CURR: 5,
            DECLARE_CMP: 6,
            IF_FOUND: 7,
            SPLAY_FOUND: 8,
            RETURN_TRUE: 9,
            ADVANCE_CURRENT: 11,
            SPLAY_LAST: 13,
            RETURN_FALSE: 14,

            // splay(NodoSplay<T> x)
            SPLAY_WHILE: 20,
            SPLAY_DECLARE_P: 21,
            SPLAY_DECLARE_G: 22,
            IF_G_NULL: 24,
            IF_X_LEFT_ZIG: 26,
            ZIG_ROTATE_RIGHT_P: 27,
            ELSE_X_RIGHT_ZIG: 28,
            ZIG_ROTATE_LEFT_P: 29,
            ELSE_G_NOT_NULL: 31,
            DECL_X_IS_LEFT: 32,
            DECL_P_IS_LEFT: 33,
            IF_ZIGZIG_LL: 35,
            ZIGZIG_LL_ROT1: 37,
            ZIGZIG_LL_ROT2: 38,
            ELSE_IF_ZIGZIG_RR: 39,
            ZIGZIG_RR_ROT1: 41,
            ZIGZIG_RR_ROT2: 42,
            ELSE_IF_ZIGZAG_LR: 43,
            ZIGZAG_LR_ROT1: 45,
            ZIGZAG_LR_ROT2: 46,
            ELSE_ZIGZAG_RL: 47,
            ZIGZAG_RL_ROT1: 49,
            ZIGZAG_RL_ROT2: 50,
            SET_ROOT_END: 54,

            // rotacionDerecha(NodoSplay<T> y)
            ROT_R_DECL_X: 60,
            ROT_R_DECL_T2: 61,
            ROT_R_SET_X_PARENT: 63,
            ROT_R_IF_Y_PARENT_NULL: 64,
            ROT_R_SET_ROOT: 65,
            ROT_R_ELSE_IF_Y_IS_RIGHT: 66,
            ROT_R_SET_PARENT_RIGHT: 67,
            ROT_R_ELSE_Y_IS_LEFT: 68,
            ROT_R_SET_PARENT_LEFT: 69,
            ROT_R_SET_X_RIGHT: 72,
            ROT_R_SET_Y_PARENT: 73,
            ROT_R_SET_Y_LEFT: 75,
            ROT_R_IF_T2_NOT_NULL: 76,
            ROT_R_SET_T2_PARENT: 77,

            // rotacionIzquierda(NodoSplay<T> x)
            ROT_L_DECL_Y: 84,
            ROT_L_DECL_T2: 85,
            ROT_L_SET_Y_PARENT: 87,
            ROT_L_IF_X_PARENT_NULL: 88,
            ROT_L_SET_ROOT: 89,
            ROT_L_ELSE_IF_X_IS_LEFT: 90,
            ROT_L_SET_PARENT_LEFT: 91,
            ROT_L_ELSE_X_IS_RIGHT: 92,
            ROT_L_SET_PARENT_RIGHT: 93,
            ROT_L_SET_Y_LEFT: 96,
            ROT_L_SET_X_PARENT: 97,
            ROT_L_SET_X_RIGHT: 99,
            ROT_L_IF_T2_NOT_NULL: 100,
            ROT_L_SET_T2_PARENT: 101
        }
    },
    getInOrder: {
        lines: [
            `/**
 * Método que realiza el recorrido inorden del árbol Splay.
 * @return Lista con la información de los nodos del árbol en secuencia inorden.
 */`,
            `public ListaCD<T> getInOrder() {`,
            `    ListaCD<T> nodos = new ListaCD<>();`,
            `    this.getInOrder(this.raiz, nodos);`,
            `    return nodos;`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza el recorrido inorden en el subárbol dado.
 * @param r Nodo raíz del subárbol actual.
 * @param nodos Lista donde se almacenan la información de los nodos visitados en secuencia inorden.
 */`,
            `private void getInOrder(NodoSplay<T> r, ListaCD<T> nodos) {`,
            `    if (r == null) {`,
            `        return;`,
            `    }`,
            `    this.getInOrder(r.izquierdo, nodos);`,
            `    nodos.insertLast(r.info);`,
            `    this.getInOrder(r.derecho, nodos);`,
            `}`,
        ],
        labels: {
            DECLARE_LIST: 2,
            CALL_RECURSIVE_INORDER: 3,
            RETURN_LIST: 4,

            // Método getInOrder(NodoSplay<T> r, ListaCD<T> nodos)
            IF_NULL_NODE: 10,
            RETURN_NULL: 11,
            CALL_LEFT: 13,
            VISIT_NODE: 14,
            CALL_RIGHT: 15
        }
    },
    getPreOrder: {
        lines: [
            `/**
 * Método que realiza el recorrido preorden del árbol Splay.
 * @return Lista con la información de los nodos del árbol en secuencia preorden.
 */`,
            `public ListaCD<T> getPreOrder() {`,
            `    ListaCD<T> nodos = new ListaCD<>();`,
            `    this.getPreOrder(this.raiz, nodos);`,
            `    return nodos;`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza el recorrido preorden en el subárbol dado.
 * @param r Nodo raíz del subárbol actual.
 * @param nodos Lista donde se almacenan la información de los nodos visitados en secuencia preorden.
 */`,
            `private void getPreOrder(NodoSplay<T> r, ListaCD<T> nodos) {`,
            `    if (r == null) {`,
            `        return;`,
            `    }`,
            `    nodos.insertLast(r.info);`,
            `    this.getPreOrder(r.izquierdo, nodos);`,
            `    this.getPreOrder(r.derecho, nodos);`,
            `}`,
        ],
        labels: {
            DECLARE_LIST: 2,
            CALL_RECURSIVE_INORDER: 3,
            RETURN_LIST: 4,

            // Método getPreOrder(NodoSplay<T> r, ListaCD<T> nodos)
            IF_NULL_NODE: 10,
            RETURN_NULL: 11,
            VISIT_NODE: 13,
            CALL_LEFT: 14,
            CALL_RIGHT: 15
        }
    },
    getPostOrder: {
        lines: [
            `/**
 * Método que realiza el recorrido postorden del árbol Splay.
 * @return Lista con la información de los nodos del árbol en secuencia postorden.
 */`,
            `public ListaCD<T> getPostOrder() {`,
            `    ListaCD<T> nodos = new ListaCD<>();`,
            `    this.getPostOrder(this.raiz, nodos);`,
            `    return nodos;`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza el recorrido postorden en el subárbol dado.
 * @param r Nodo raíz del subárbol actual.
 * @param nodos Lista donde se almacenan la información de los nodos visitados en secuencia postorden.
 */`,
            `private void getPostOrder(NodoSplay<T> r, ListaCD<T> nodos) {`,
            `    if (r == null) {`,
            `        return;`,
            `    }`,
            `    this.getPostOrder(r.izquierdo, nodos);`,
            `    this.getPostOrder(r.derecho, nodos);`,
            `    nodos.insertLast(r.info);`,
            `}`,
        ],
        labels: {
            DECLARE_LIST: 2,
            CALL_RECURSIVE_INORDER: 3,
            RETURN_LIST: 4,

            // Método getPostOrder(NodoSplay<T> r, ListaCD<T> nodos)
            IF_NULL_NODE: 10,
            RETURN_NULL: 11,
            CALL_LEFT: 13,
            CALL_RIGHT: 14,
            VISIT_NODE: 15,
        }
    },
    getLevelOrder: {
        lines: [
            `/**
 * Método que realiza el recorrido por niveles del árbol Splay.
 * @return Lista con la información de los nodos del árbol por niveles.
 */`,
            `public ListaCD<T> getLevelOrder() {`,
            `    ListaCD<T> nodos = new ListaCD<>();`,
            `    if (this.raiz != null) {`,
            `        Cola<NodoSplay<T>> cola = new Cola<>();`,
            `        cola.enqueue(this.raiz);`,
            `        \n`,
            `        while (!cola.isEmpty()) {`,
            `             NodoSplay<T> nodo = cola.dequeue();`,
            `             nodos.insertLast(nodo.info);`,
            `             if (nodo.izquierdo != null) {`,
            `                 cola.enqueue(nodo.izquierdo);`,
            `             }`,
            `             if (nodo.derecho != null) {`,
            `                 cola.enqueue(nodo.derecho);`,
            `             }`,
            `        }`,
            `    }`,
            `    return nodos;`,
            `}`,
        ],
        labels: {
            DECLARE_LIST: 2,
            VALIDATE_EMPTY: 3,
            DECLARE_QUEUE: 4,
            ENQUEUE_ROOT: 5,
            WHILE_CHECK: 7,
            DEQUEUE_NODE: 8,
            VISIT_NODE: 9,
            IF_LEFT_NOT_NULL: 10,
            ENQUEUE_LEFT: 11,
            IF_RIGHT_NOT_NULL: 13,
            ENQUEUE_RIGHT: 14,
            RETURN_LIST: 18
        }
    },
    clean: {
        lines: [
            `/**
 * Método que elimina todos los nodos del árbol Splay.
 */`,
            `public void clean() {`,
            `    this.raiz = null;`,
            `}`,
        ],
        labels: {
            CLEAR_ROOT: 2
        }
    }
});