import { OperationCode } from "./typesPseudoCode";

export const getArbolSplayCode = (): Record<string, OperationCode> => ({
    insert: {
        lines: [
            `/**
 * Método que inserta un nuevo elemento en el árbol Splay.
 * - Si el elemento ya existe: se aplica splay del nodo encontrado para moverlo a la raíz.
 * - Si no existe: se inserta como BST y luego se aplica splay del nuevo nodo para moverlo a la raíz 
 * 
 * @param valor Elemento a insertar o acceder.
 * @return true si el elemento fue insertado, false si ya existía.
 */`,
            `public boolean insertar(T {0}) {`,
            `    NodoSplay<T> p = null;`,
            `    NodoSplay<T> cur = this.raiz;`,
            `    while (cur != null) {`,
            `        int cmp = {0}.compareTo(cur.info);`,
            `        if (cmp == 0) {`,
            `            this.splay(cur);`,
            `            return false;`,
            `        }`,
            `        p = cur;`,
            `        cur = cmp < 0 ? cur.izquierdo : cur.derecho;`,
            `    }`,
            `    NodoSplay<T> x = new NodoSplay<>({0});`,
            `    x.padre = p;`,
            `    if (p == null) {`,
            `        this.raiz = x;`,
            `    } else if (x.info.compareTo(p.info) < 0) {`,
            `        p.izquierdo = x;`,
            `    } else {`,
            `        p.derecho = x;`,
            `    }`,
            `    this.splay(x);`,
            `    {1}++`,
            `    return true;`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza la operación de splay sobre el nodo dado, moviéndolo hasta la raíz
 * mediante rotaciones Zig, Zig-Zig o Zig-Zag según corresponda:
 * 
 * 1. Zig: Nodo es hijo directo de la raíz -> una rotación.
 * 2. Zig-Zig: Nodo y padre son ambos hijos izquierdos o derechos -> dos rotaciones en la misma dirección.
 * 3. Zig-Zag: Nodo y padre están en direcciones opuestas -> dos rotaciones en direcciones distintas.
 * 
 * @param x Nodo a splayear hasta la raíz.
 */`,
            `private void splay(NodoSplay<T> x) {`,
            `    while (x.padre != null) {`,
            `        NodoSplay<T> p = x.padre;`,
            `        NodoSplay<T> g = p.padre;`,
            `\n`,
            `        if (g == null) {`,
            `            // Zig`,
            `            if (x == p.izquierdo) {`,
            `                this.rotacionDerecha(p);`,
            `            } else {`,
            `                this.rotacionIzquierda(p);`,
            `            }`,
            `        } else {`,
            `            boolean xIsLeft = x == p.izquierdo;`,
            `            boolean pIsLeft = p == g.izquierdo;`,
            `\n`,
            `            if (xIsLeft && pIsLeft) {`,
            `                // Zig-Zig LL`,
            `                this.rotacionDerecha(g);`,
            `                this.rotacionDerecha(p);`,
            `            } else if (!xIsLeft && !pIsLeft) {`,
            `                // Zig-Zig RR`,
            `                this.rotacionIzquierda(g);`,
            `                this.rotacionIzquierda(p);`,
            `            } else if (!xIsLeft && pIsLeft) {`,
            `                // Zig-Zag LR`,
            `                this.rotacionIzquierda(p);`,
            `                this.rotacionDerecha(g);`,
            `            } else {`,
            `                // Zig-Zag RL`,
            `                this.rotacionDerecha(p);`,
            `                this.rotacionIzquierda(g);`,
            `            }`,
            `        }`,
            `    }`,
            `    this.raiz = x;`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza una rotación simple a la derecha en el subárbol dado.
 * @param y Nodo raíz del subárbol a rotar.
 */`,
            `private void rotacionDerecha(NodoSplay<T> y) {`,
            `    NodoSplay<T> x = y.izquierdo;`,
            `    NodoSplay<T> T2 = x.derecho;`,
            `\n`,
            `    x.padre = y.padre;`,
            `    if (y.padre == null) {`,
            `        this.raiz = x;`,
            `    } else if (y == y.padre.derecho) {`,
            `        y.padre.derecho = x;`,
            `    } else {`,
            `        y.padre.izquierdo = x;`,
            `    }`,
            `\n`,
            `    x.derecho = y;`,
            `    y.padre = x;`,
            `\n`,
            `    y.izquierdo = T2;`,
            `    if (T2 != null) {`,
            `        T2.padre = y;`,
            `    }`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza una rotación simple a la izquierda en el subárbol dado.
 * @param x Nodo raíz del subárbol a rotar.
 */`,
            `private void rotacionIzquierda(NodoSplay<T> x) {`,
            `    NodoSplay<T> y = x.derecho;`,
            `    NodoSplay<T> T2 = y.izquierdo;`,
            `\n`,
            `    y.padre = x.padre;`,
            `    if (x.padre == null) {`,
            `        this.raiz = y;`,
            `    } else if (x == x.padre.izquierdo) {`,
            `        x.padre.izquierdo = y;`,
            `    } else {`,
            `        x.padre.derecho = y;`,
            `    }`,
            `\n`,
            `    y.izquierdo = x;`,
            `    x.padre = y;`,
            `\n`,
            `    x.derecho = T2;`,
            `    if (T2 != null) {`,
            `        T2.padre = x;`,
            `    }`,
            `}`,
        ],
        labels: {
            DECLARE_PARENT: 2,
            DECLARE_CURSOR: 3,
            BST_WHILE: 4,
            DECLARE_CMP: 5,
            IF_DUPLICATE: 6,
            SPLAY_EXISTING: 7,
            RETURN_FALSE: 8,
            SET_PARENT: 10,
            ADVANCE_CURSOR: 11,
            CREATE_NODE: 13,
            SET_NODE_PARENT: 14,
            IF_P_NULL: 15,
            SET_ROOT: 16,
            ELSE_IF_ATTACH_LEFT: 17,
            ATTACH_NODE_LEFT: 18,
            ELSE_ATTACH_RIGHT: 19,
            ATTACH_NODE_RIGHT: 20,
            SPLAY_NEW: 22,
            INC_SIZE: 23,
            RETURN_TRUE: 24,

            // splay(NodoSplay<T> x)
            SPLAY_WHILE: 30,
            SPLAY_DECLARE_P: 31,
            SPLAY_DECLARE_G: 32,
            IF_G_NULL: 34,
            IF_X_LEFT_ZIG: 36,
            ZIG_ROTATE_RIGHT_P: 37,
            ELSE_X_RIGHT_ZIG: 38,
            ZIG_ROTATE_LEFT_P: 39,
            ELSE_G_NOT_NULL: 41,
            DECL_X_IS_LEFT: 42,
            DECL_P_IS_LEFT: 43,
            IF_ZIGZIG_LL: 45,
            ZIGZIG_LL_ROT1: 47,
            ZIGZIG_LL_ROT2: 48,
            ELSE_IF_ZIGZIG_RR: 49,
            ZIGZIG_RR_ROT1: 51,
            ZIGZIG_RR_ROT2: 52,
            ELSE_IF_ZIGZAG_LR: 53,
            ZIGZAG_LR_ROT1: 55,
            ZIGZAG_LR_ROT2: 56,
            ELSE_ZIGZAG_RL: 57,
            ZIGZAG_RL_ROT1: 59,
            ZIGZAG_RL_ROT2: 60,
            SET_ROOT_END: 64,

            // rotacionDerecha(NodoSplay<T> y)
            ROT_R_DECL_X: 70,
            ROT_R_DECL_T2: 71,
            ROT_R_SET_X_PARENT: 73,
            ROT_R_IF_Y_PARENT_NULL: 74,
            ROT_R_SET_ROOT: 75,
            ROT_R_ELSE_IF_Y_IS_RIGHT: 76,
            ROT_R_SET_PARENT_RIGHT: 77,
            ROT_R_ELSE_Y_IS_LEFT: 78,
            ROT_R_SET_PARENT_LEFT: 79,
            ROT_R_SET_X_RIGHT: 82,
            ROT_R_SET_Y_PARENT: 83,
            ROT_R_SET_Y_LEFT: 85,
            ROT_R_IF_T2_NOT_NULL: 86,
            ROT_R_SET_T2_PARENT: 87,

            // rotacionIzquierda(NodoSplay<T> x)
            ROT_L_DECL_Y: 94,
            ROT_L_DECL_T2: 95,
            ROT_L_SET_Y_PARENT: 97,
            ROT_L_IF_X_PARENT_NULL: 98,
            ROT_L_SET_ROOT: 99,
            ROT_L_ELSE_IF_X_IS_LEFT: 100,
            ROT_L_SET_PARENT_LEFT: 101,
            ROT_L_ELSE_X_IS_RIGHT: 102,
            ROT_L_SET_PARENT_RIGHT: 103,
            ROT_L_SET_Y_LEFT: 106,
            ROT_L_SET_X_PARENT: 107,
            ROT_L_SET_X_RIGHT: 109,
            ROT_L_IF_T2_NOT_NULL: 110,
            ROT_L_SET_T2_PARENT: 111,
        }
    },
    delete: [
        `/**`,
        ` * Elimina un valor del Árbol Roji-Negro.`,
        ` * Se hace delete BST + fix-up para restaurar las propiedades.`,
        ` */`,
        `public void delete(T {0}) {`,
        `    NodoRN<T> z = buscarNodo(raiz, {0});`,
        `    if (z == null) return;`,
        ``,
        `    NodoRN<T> y = z;`,
        `    Color yColorOriginal = y.color;`,
        `    NodoRN<T> x;`,
        `    if (z.izq == null) {`,
        `        x = z.der;`,
        `        transplant(z, z.der);`,
        `    } else if (z.der == null) {`,
        `        x = z.izq;`,
        `        transplant(z, z.izq);`,
        `    } else {`,
        `        y = minimo(z.der);`,
        `        yColorOriginal = y.color;`,
        `        x = y.der;`,
        `        if (y.padre == z) {`,
        `            if (x != null) x.padre = y;`,
        `        } else {`,
        `            transplant(y, y.der);`,
        `            y.der = z.der;`,
        `            y.der.padre = y;`,
        `        }`,
        `        transplant(z, y);`,
        `        y.izq = z.izq;`,
        `        y.izq.padre = y;`,
        `        y.color = z.color;`,
        `    }`,
        `    if (yColorOriginal == NEGRO) deleteFixup(x);`,
        `}`,
        ``,
        `private void deleteFixup(NodoRN<T> x) {`,
        `    while (x != raiz && colorDe(x) == NEGRO) {`,
        `        if (x == x.padre.izq) {`,
        `            NodoRN<T> w = x.padre.der; // hermano`,
        `            if (colorDe(w) == ROJO) {`,
        `                // Caso 1`,
        `                w.color = NEGRO;`,
        `                x.padre.color = ROJO;`,
        `                rotacionIzquierda(x.padre);`,
        `                w = x.padre.der;`,
        `            }`,
        `            if (colorDe(w.izq) == NEGRO && colorDe(w.der) == NEGRO) {`,
        `                // Caso 2`,
        `                w.color = ROJO;`,
        `                x = x.padre;`,
        `            } else {`,
        `                if (colorDe(w.der) == NEGRO) {`,
        `                    // Caso 3`,
        `                    if (w.izq != null) w.izq.color = NEGRO;`,
        `                    w.color = ROJO;`,
        `                    rotacionDerecha(w);`,
        `                    w = x.padre.der;`,
        `                }`,
        `                // Caso 4`,
        `                w.color = x.padre.color;`,
        `                x.padre.color = NEGRO;`,
        `                if (w.der != null) w.der.color = NEGRO;`,
        `                rotacionIzquierda(x.padre);`,
        `                x = raiz;`,
        `            }`,
        `        } else {`,
        `            // Simétrico (x es hijo derecho)`,
        `            NodoRN<T> w = x.padre.izq;`,
        `            if (colorDe(w) == ROJO) {`,
        `                w.color = NEGRO;`,
        `                x.padre.color = ROJO;`,
        `                rotacionDerecha(x.padre);`,
        `                w = x.padre.izq;`,
        `            }`,
        `            if (colorDe(w.der) == NEGRO && colorDe(w.izq) == NEGRO) {`,
        `                w.color = ROJO;`,
        `                x = x.padre;`,
        `            } else {`,
        `                if (colorDe(w.izq) == NEGRO) {`,
        `                    if (w.der != null) w.der.color = NEGRO;`,
        `                    w.color = ROJO;`,
        `                    rotacionIzquierda(w);`,
        `                    w = x.padre.izq;`,
        `                }`,
        `                w.color = x.padre.color;`,
        `                x.padre.color = NEGRO;`,
        `                if (w.izq != null) w.izq.color = NEGRO;`,
        `                rotacionDerecha(x.padre);`,
        `                x = raiz;`,
        `            }`,
        `        }`,
        `    }`,
        `    if (x != null) x.color = NEGRO;`,
        `}`,
        ``,
        `// Utilidades:`,
        `private void transplant(NodoRN<T> u, NodoRN<T> v) {`,
        `    if (u.padre == null) raiz = v;`,
        `    else if (u == u.padre.izq) u.padre.izq = v;`,
        `    else u.padre.der = v;`,
        `    if (v != null) v.padre = u.padre;`,
        `}`,
        `private Color colorDe(NodoRN<T> n) { return (n == null) ? NEGRO : n.color; }`,
    ],
    search: [
        `/** Busca un valor (propiedad BST). */`,
        `public boolean search(T {0}) {`,
        `    NodoRN<T> x = raiz;`,
        `    while (x != null) {`,
        `        int cmp = {0}.compareTo(x.info);`,
        `        if (cmp == 0) return true;`,
        `        x = (cmp < 0) ? x.izq : x.der;`,
        `    }`,
        `    return false;`,
        `}`,
    ],
    getInOrder: {
        lines: [
            `/**
 * Método que realiza el recorrido inorden del árbol Splay.
 * @return Lista con la información de los nodos del árbol en secuencia inorden.
 */`,
            `public ListaCD<T> getInOrder() {`,
            `    ListaCD<T> nodos = new ListaCD<>();`,
            `    this.getInOrder(this.raiz, nodos);`,
            `    return nodos;`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza el recorrido inorden en el subárbol dado.
 * @param r Nodo raíz del subárbol actual.
 * @param nodos Lista donde se almacenan la información de los nodos visitados en secuencia inorden.
 */`,
            `private void getInOrder(NodoSplay<T> r, ListaCD<T> nodos) {`,
            `    if (r == null) {`,
            `        return;`,
            `    }`,
            `    this.getInOrder(r.izquierdo, nodos);`,
            `    nodos.insertLast(r.info);`,
            `    this.getInOrder(r.derecho, nodos);`,
            `}`,
        ],
        labels: {
            DECLARE_LIST: 2,
            CALL_RECURSIVE_INORDER: 3,
            RETURN_LIST: 4,

            // Método getInOrder(NodoSplay<T> r, ListaCD<T> nodos)
            IF_NULL_NODE: 10,
            RETURN_NULL: 11,
            CALL_LEFT: 13,
            VISIT_NODE: 14,
            CALL_RIGHT: 15
        }
    },
    getPreOrder: {
        lines: [
            `/**
 * Método que realiza el recorrido preorden del árbol Splay.
 * @return Lista con la información de los nodos del árbol en secuencia preorden.
 */`,
            `public ListaCD<T> getPreOrder() {`,
            `    ListaCD<T> nodos = new ListaCD<>();`,
            `    this.getPreOrder(this.raiz, nodos);`,
            `    return nodos;`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza el recorrido preorden en el subárbol dado.
 * @param r Nodo raíz del subárbol actual.
 * @param nodos Lista donde se almacenan la información de los nodos visitados en secuencia preorden.
 */`,
            `private void getPreOrder(NodoSplay<T> r, ListaCD<T> nodos) {`,
            `    if (r == null) {`,
            `        return;`,
            `    }`,
            `    nodos.insertLast(r.info);`,
            `    this.getPreOrder(r.izquierdo, nodos);`,
            `    this.getPreOrder(r.derecho, nodos);`,
            `}`,
        ],
        labels: {
            DECLARE_LIST: 2,
            CALL_RECURSIVE_INORDER: 3,
            RETURN_LIST: 4,

            // Método getPreOrder(NodoSplay<T> r, ListaCD<T> nodos)
            IF_NULL_NODE: 10,
            RETURN_NULL: 11,
            VISIT_NODE: 13,
            CALL_LEFT: 14,
            CALL_RIGHT: 15
        }
    },
    getPostOrder: {
        lines: [
            `/**
 * Método que realiza el recorrido postorden del árbol Splay.
 * @return Lista con la información de los nodos del árbol en secuencia postorden.
 */`,
            `public ListaCD<T> getPostOrder() {`,
            `    ListaCD<T> nodos = new ListaCD<>();`,
            `    this.getPostOrder(this.raiz, nodos);`,
            `    return nodos;`,
            `}`,
            `\n`,
            `\n`,
            `/**
 * Método auxiliar que realiza el recorrido postorden en el subárbol dado.
 * @param r Nodo raíz del subárbol actual.
 * @param nodos Lista donde se almacenan la información de los nodos visitados en secuencia postorden.
 */`,
            `private void getPostOrder(NodoSplay<T> r, ListaCD<T> nodos) {`,
            `    if (r == null) {`,
            `        return;`,
            `    }`,
            `    this.getPostOrder(r.izquierdo, nodos);`,
            `    this.getPostOrder(r.derecho, nodos);`,
            `    nodos.insertLast(r.info);`,
            `}`,
        ],
        labels: {
            DECLARE_LIST: 2,
            CALL_RECURSIVE_INORDER: 3,
            RETURN_LIST: 4,

            // Método getPostOrder(NodoSplay<T> r, ListaCD<T> nodos)
            IF_NULL_NODE: 10,
            RETURN_NULL: 11,
            CALL_LEFT: 13,
            CALL_RIGHT: 14,
            VISIT_NODE: 15,
        }
    },
    getLevelOrder: {
        lines: [
            `/**
 * Método que realiza el recorrido por niveles del árbol Splay.
 * @return Lista con la información de los nodos del árbol por niveles.
 */`,
            `public ListaCD<T> getLevelOrder() {`,
            `    ListaCD<T> nodos = new ListaCD<>();`,
            `    if (this.raiz != null) {`,
            `        Cola<NodoSplay<T>> cola = new Cola<>();`,
            `        cola.enqueue(this.raiz);`,
            `        \n`,
            `        while (!cola.isEmpty()) {`,
            `             NodoSplay<T> nodo = cola.dequeue();`,
            `             nodos.insertLast(nodo.info);`,
            `             if (nodo.izquierdo != null) {`,
            `                 cola.enqueue(nodo.izquierdo);`,
            `             }`,
            `             if (nodo.derecho != null) {`,
            `                 cola.enqueue(nodo.derecho);`,
            `             }`,
            `        }`,
            `    }`,
            `    return nodos;`,
            `}`,
        ],
        labels: {
            DECLARE_LIST: 2,
            VALIDATE_EMPTY: 3,
            DECLARE_QUEUE: 4,
            ENQUEUE_ROOT: 5,
            WHILE_CHECK: 7,
            DEQUEUE_NODE: 8,
            VISIT_NODE: 9,
            IF_LEFT_NOT_NULL: 10,
            ENQUEUE_LEFT: 11,
            IF_RIGHT_NOT_NULL: 13,
            ENQUEUE_RIGHT: 14,
            RETURN_LIST: 18
        }
    },
    clean: {
        lines: [
            `/**
 * Método que elimina todos los nodos del árbol Splay.
 */`,
            `public void clean() {`,
            `    this.raiz = null;`,
            `}`,
        ],
        labels: {
            CLEAR_ROOT: 2
        }
    }
});