import { OperationCode } from "./typesPseudoCode";

export const getArbolRNCode = (): Record<string, OperationCode> => ({
  insert: {
    lines: [
      `/**
 * Método que inserta un nuevo elemento en el árbol Rojo-Negro.
 * @param valor Elemento a insertar.
 * @return true si el elemento fue insertado, false si ya existía.
 */`,
      `public boolean insert(T {0}) {`,
      `    NodoRN<T> y = null;`,
      `    NodoRN<T> x = this.raiz;`,
      `    while (x != null) {`,
      `        int cmp = {0}.compareTo(x.info);`,
      `        if (cmp == 0) {`,
      `            return false;`,
      `        }`,
      `        y = x;`,
      `        x = cmp < 0 ? x.izquierdo : x.derecho;`,
      `    }`,
      `    NodoRN<T> z = new NodoRN<>({0}, 0);`,
      `    z.padre = y;`,
      `    if (y == null) {`,
      `        this.raiz = z;`,
      `    } else if (z.info.compareTo(y.info) < 0) {`,
      `        y.izquierdo = z;`,
      `    } else {`,
      `        y.derecho = z;`,
      `    }`,
      `    this.insertFixup(z);`,
      `    {1}++;`,
      `    return true;`,
      `}`,
      `\n`,
      `\n`,
      `/**
 * Método auxiliar que restaura las propiedades del árbol Rojo-Negro tras la inserción de un nuevo nodo,
 * aplicando los diferentes casos de corrección según sea necesario:
 * 
 * 1. Tío rojo -> recoloreo y propagación hacia arriba.
 * 2. Configuración en triángulo -> rotación en el padre.
 * 3. Configuración en línea -> recoloreo y rotación en el abuelo.
 * 
 * @param z Nodo recién insertado que puede inflingir las propiedades del árbol.
 */`,
      `private void insertFixup(NodoRN<T> z) {`,
      `    while (z.padre != null && z.padre.color == 0) {`,
      `        NodoRN<T> p = z.padre;`,
      `        NodoRN<T> g = p.padre;`,
      `        if (p == g.izquierdo) {`,
      `            NodoRN<T> y = g.derecho;`,
      `\n`,
      `            if (y != null && y.color == 0) {`,
      `                // Caso 1: Tío rojo`,
      `                this.recolor(p, 1);`,
      `                this.recolor(y, 1);`,
      `                this.recolor(g, 0);`,
      `                z = g;`,
      `            } else {`,
      `                // Caso 2: Configuración en triángulo`,
      `                if (z == p.derecho) {`,
      `                    z = p;`,
      `                    this.rotacionIzquierda(z);`,
      `                    p = z.padre;`,
      `                }`,
      `                // Caso 3: Configuración en línea`,
      `                this.recolor(p, 1);`,
      `                this.recolor(g, 0);`,
      `                this.rotacionDerecha(g);`,
      `            }`,
      `        } else {`,
      `            // espejo: p es hijo derecho`,
      `            NodoRN<T> y = g.izquierdo;`,
      `\n`,
      `            if (y != null && y.color == 0) {`,
      `                // Caso 1: Tío rojo`,
      `                this.recolor(p, 1);`,
      `                this.recolor(y, 1);`,
      `                this.recolor(g, 0);`,
      `                z = g;`,
      `            } else {`,
      `                // Caso 2: Configuración en triángulo`,
      `                if (z == p.izquierdo) {`,
      `                    z = p;`,
      `                    this.rotacionDerecha(z);`,
      `                    p = z.padre;`,
      `                }`,
      `                // Caso 3: Configuración en línea`,
      `                this.recolor(p, 1);`,
      `                this.recolor(g, 0);`,
      `                this.rotacionIzquierda(g);`,
      `            }`,
      `        }`,
      `    }`,
      `\n`,
      `    // Asegurar raíz negra`,
      `    if (this.raiz != null && this.raiz.color != 1) {`,
      `        this.recolor(this.raiz, 1);`,
      `    }`,
      `}`,
      `\n`,
      `\n`,
      `/**
 * Método auxiliar que modifica el color del nodo dado.
 * @param n Nodo cuyo color se va a modificar.
 * @param to Nuevo color del nodo.
 */`,
      `private void recolor(NodoRN<T> n, int to) {`,
      `    if (n == null) {`,
      `        return;`,
      `    }`,
      `    n.color = to;`,
      `}`,
      `\n`,
      `\n`,
      `/**
 * Método auxiliar que realiza una rotación simple a la derecha en el subárbol dado.
 * @param y Nodo raíz del subárbol a rotar.
 */`,
      `private void rotacionDerecha(NodoRN<T> y) {`,
      `    NodoRN<T> x = y.izquierdo;`,
      `    NodoRN<T> T2 = x.derecho;`,
      `\n`,
      `    x.padre = y.padre;`,
      `    if (y.padre == null) {`,
      `        this.raiz = x;`,
      `    } else if (y == y.padre.derecho) {`,
      `        y.padre.derecho = x;`,
      `    } else {`,
      `        y.padre.izquierdo = x;`,
      `    }`,
      `\n`,
      `    x.derecho = y;`,
      `    y.padre = x;`,
      `\n`,
      `    y.izquierdo = T2;`,
      `    if (T2 != null) {`,
      `        T2.padre = y;`,
      `    }`,
      `}`,
      `\n`,
      `\n`,
      `/**
 * Método auxiliar que realiza una rotación simple a la izquierda en el subárbol dado.
 * @param x Nodo raíz del subárbol a rotar.
 */`,
      `private void rotacionIzquierda(NodoRN<T> x) {`,
      `    NodoRN<T> y = x.derecho;`,
      `    NodoRN<T> T2 = y.izquierdo;`,
      `\n`,
      `    y.padre = x.padre;`,
      `    if (x.padre == null) {`,
      `        this.raiz = y;`,
      `    } else if (x == x.padre.izquierdo) {`,
      `        x.padre.izquierdo = y;`,
      `    } else {`,
      `        x.padre.derecho = y;`,
      `    }`,
      `\n`,
      `    y.izquierdo = x;`,
      `    x.padre = y;`,
      `\n`,
      `    x.derecho = T2;`,
      `    if (T2 != null) {`,
      `        T2.padre = x;`,
      `    }`,
      `}`,
    ],
    labels: {
      DECLARE_PARENT: 2,
      DECLARE_CURSOR: 3,
      BST_WHILE: 4,
      DECLARE_CMP: 5,
      IF_DUPLICATE: 6,
      RETURN_FALSE: 7,
      SET_Y_PARENT: 9,
      ADVANCE_CURSOR: 10,
      CREATE_LEAF_NODE: 12,
      SET_LEAF_PARENT: 13,
      VALIDATE_EMPTY: 14,
      SET_ROOT_NODE: 15,
      ELSE_IF_ATTACH_LEFT: 16,
      ATTACH_NODE_LEFT: 17,
      ELSE_ATTACH_RIGHT: 18,
      ATTACH_NODE_RIGHT: 19,
      CALL_FIXUP: 21,
      INC_SIZE: 22,
      RETURN_TRUE: 23,

      // insertFixup(z)
      FIXUP_WHILE_CHECK: 29,
      DECL_P: 30,
      DECL_G: 31,

      // Padre izquierdo
      IF_PARENT_IS_LEFT_CHILD: 32,
      SET_UNCLE_RIGHT: 33,
      IF_UNCLE_RED_LEFT: 35,
      CASE1_LEFT_RECOLOR_P: 37,
      CASE1_LEFT_RECOLOR_Y: 38,
      CASE1_LEFT_RECOLOR_G: 39,
      CASE1_LEFT_SET_Z_G: 40,
      ELSE_UNCLE_RED_LEFT: 41,
      IF_TRIANGLE_LEFT: 43,
      CASE2_LEFT_SET_Z_P: 44,
      CASE2_LEFT_ROTATE_LEFT_P: 45,
      CASE2_LEFT_UPDATE_P: 46,
      CASE3_LEFT_RECOLOR_P: 49,
      CASE3_LEFT_RECOLOR_G: 50,
      CASE3_LEFT_ROTATE_RIGHT_G: 51,

      // Rama simétrica (padre derecho)
      ELSE_PARENT_IS_RIGHT_CHILD: 53,
      SET_UNCLE_LEFT: 55,
      IF_UNCLE_RED_RIGHT: 57,
      CASE1_RIGHT_RECOLOR_P: 59,
      CASE1_RIGHT_RECOLOR_Y: 60,
      CASE1_RIGHT_RECOLOR_G: 61,
      CASE1_RIGHT_SET_Z_G: 62,
      ELSE_UNCLE_RED_RIGHT: 63,
      IF_TRIANGLE_RIGHT: 65,
      CASE2_RIGHT_SET_Z_P: 66,
      CASE2_RIGHT_ROTATE_RIGHT_P: 67,
      CASE2_RIGHT_UPDATE_P: 68,
      CASE3_RIGHT_RECOLOR_P: 71,
      CASE3_RIGHT_RECOLOR_G: 72,
      CASE3_RIGHT_ROTATE_LEFT_G: 73,

      // Verificación de raíz negra
      IF_ROOT_NOT_BLACK: 79,
      RECOLOR_ROOT_BLACK: 80,

      // recolor(NodoRN<T> n, int to)
      VALIDATE_NULL_NODE: 87,
      RETURN_NULL_GUARD: 88,
      RECOLOR_ASSIGN: 90,

      // rotacionDerecha(NodoRN<T> y)
      ROT_RIGHT_DECL_X: 96,
      ROT_RIGHT_DECL_T2: 97,
      ROT_RIGHT_SET_X_PARENT: 99,
      ROT_RIGHT_IF_Y_PARENT_NULL: 100,
      ROT_RIGHT_SET_ROOT: 101,
      ROT_RIGHT_ELSE_IF_Y_RIGHT: 102,
      ROT_RIGHT_SET_Y_PARENT_RIGHT: 103,
      ROT_RIGHT_ELSE_Y_LEFT: 104,
      ROT_RIGHT_SET_Y_PARENT_LEFT: 105,
      ROT_RIGHT_SET_X_RIGHT: 108,
      ROT_RIGHT_SET_Y_PARENT: 109,
      ROT_RIGHT_SET_Y_LEFT: 111,
      ROT_RIGHT_IF_T2_NOT_NULL: 112,
      ROT_RIGHT_SET_T2_PARENT: 113,

      // rotacionIzquierda(NodoRN<T> x)
      ROT_LEFT_DECL_Y: 120,
      ROT_LEFT_DECL_T2: 121,
      ROT_LEFT_SET_Y_PARENT: 123,
      ROT_LEFT_IF_X_PARENT_NULL: 124,
      ROT_LEFT_SET_ROOT: 125,
      ROT_LEFT_ELSE_IF_X_LEFT: 126,
      ROT_LEFT_SET_X_PARENT_LEFT: 127,
      ROT_LEFT_ELSE_X_RIGHT: 128,
      ROT_LEFT_SET_X_PARENT_RIGHT: 129,
      ROT_LEFT_SET_Y_LEFT: 132,
      ROT_LEFT_SET_X_PARENT: 133,
      ROT_LEFT_SET_X_RIGHT: 135,
      ROT_LEFT_IF_T2_NOT_NULL: 136,
      ROT_LEFT_SET_T2_PARENT: 137
    }
  },
  delete: {
    lines: [
      `/**
 * Método que elimina el elemento especificado del árbol Rojo-Negro.
 * @param valor Elemento a eliminar.
 * @return true si el elemento fue eliminado, false si no existe en el árbol.
 * @throws RuntimeException si el árbol está vacío.
 */`,
      `public boolean delete(T {0}) {`,
      `    if (this.raiz == null) {`,
      `        throw new RuntimeException("No fue posible eliminar el nodo: El árbol se encuentra vacío (cantidad de nodos: 0).");`,
      `    }`,
      `    NodoRN<T> z = this.raiz;`,
      `    while (z != null) {`,
      `        int cmp = {0}.compareTo(z.info);`,
      `        if (cmp == 0) break;`,
      `        z = cmp < 0 ? z.izquierdo : z.derecho;`,
      `    }`,
      `\n`,
      `    if (z == null) return false;`,
      `\n`,
      `    NodoRN<T> y = z;`,
      `    int yOriginalColor = y.color;`,
      `\n`,
      `    NodoRN<T> x;`,
      `    NodoRN<T> xParent;`,
      `\n`,
      `    if (z.izquierdo == null) {`,
      `        x = z.derecho;`,
      `        xParent = z.padre;`,
      `        this.transplantar(z, z.derecho);`,
      `    } else if (z.derecho == null) {`,
      `        x = z.izquierdo;`,
      `        xParent = z.padre;`,
      `        this.transplantar(z, z.izquierdo);`,
      `    } else {`,
      `        NodoRN<T> succ = z.derecho;`,
      `        while (succ.izquierdo != null) {`,
      `            succ = succ.izquierdo;`,
      `        }`,
      `        y = succ;`,
      `        yOriginalColor = y.color;`,
      `        x = y.derecho;`,
      `\n`,
      `        if (y.padre == z) {`,
      `            xParent = y;`,
      `        } else {`,
      `            this.transplantar(y, y.derecho);`,
      `            y.derecho = z.derecho;`,
      `            if (y.derecho != null) {`,
      `                y.derecho.padre = y;`,
      `            }`,
      `            xParent = y.padre;`,
      `        }`,
      `        this.transplantar(z, y);`,
      `        y.izquierdo = z.izquierdo;`,
      `        if (y.izquierdo != null) {`,
      `            y.izquierdo.padre = y;`,
      `        }`,
      `        this.recolor(y, z.color);`,
      `    }`,
      `\n`,
      `    if (yOriginalColor == 1) {`,
      `        this.deleteFixup(x, xParent);`,
      `    }`,
      `    {1}--;`,
      `    return true;`,
      `}`,
      `\n`,
      `\n`,
      `/**
 * Método auxiliar que restaura las propiedades del árbol Rojo-Negro tras la eliminación de un nodo,
 * aplicando los diferentes casos de corrección según sea necesario:
 * 
 * 1. Hermano rojo -> recoloreo y rotación en el padre.
 * 2. Hermano negro con hijos negros -> recoloreo y propagación hacia arriba.
 * 3. Hermano negro con hijo cercano rojo -> recoloreo y rotación en el hermano.
 * 4. Hermano negro con hijo lejano rojo -> recoloreo y rotación en el padre.
 * 
 * @param x Nodo desde el cual se inicia la restauración.
 * @param xParent Padre del nodo x, usado como referencia cuando x es null.
 */`,
      `private void deleteFixup(NodoRN<T> x, NodoRN<T> xParent) {`,
      `    while (x != this.raiz && (x == null || x.color == 1)) {`,
      `        NodoRN<T> p = x != null ? x.padre : xParent;`,
      `        if (p == null) break;`,
      `\n`,
      `        boolean xEsIzq = p.izquierdo == x;`,
      `        NodoRN<T> w = xEsIzq ? p.derecho : p.izquierdo;`,
      `\n`,
      `        if (w != null && w.color == 0) {`,
      `            // Caso 1: Hermano rojo`,
      `            this.recolor(w, 1);`,
      `            this.recolor(p, 0);`,
      `            if (xEsIzq) {`,
      `                this.rotacionIzquierda(p);`,
      `            } else {`,
      `                this.rotacionDerecha(p);`,
      `            }`,
      `            xParent = x != null ? x.padre : xParent;`,
      `            w = xEsIzq ? xParent.derecho : xParent.izquierdo;`,
      `        }`,
      `\n`,
      `        NodoRN<T> wLeft = w != null ? w.izquierdo : null;`,
      `        NodoRN<T> wRight = w != null ? w.derecho : null;`,
      `\n`,
      `        if ((wLeft == null || wLeft.color == 1) && (wRight == null || wRight.color == 1)) {`,
      `            // Caso 2: Hermano negro con hijos negros`,
      `            if (w != null) {`,
      `                this.recolor(w, 0);`,
      `            }`,
      `            x = p;`,
      `            xParent = p.padre;`,
      `            continue;`,
      `        }`,
      `\n`,
      `        if (xEsIzq) {`,
      `            // Caso 3: Hermano negro con hijo cercano rojo (w.izquierdo), hijo lejano negro (w.derecho)`,
      `            if (wRight == null || wRight.color == 1) {`,
      `                if (wLeft != null) {`,
      `                    this.recolor(wLeft, 1);`,
      `                }`,
      `                if (w != null) {`,
      `                    this.recolor(w, 0);`,
      `                    this.rotacionDerecha(w);`,
      `                }`,
      `                xParent = x != null ? x.padre : xParent;`,
      `                w = xParent.derecho;`,
      `            }`,
      `            // Caso D: Hermano negro con hijo lejano rojo`,
      `            if (w != null) {`,
      `                this.recolor(w, p != null ? p.color : 1);`,
      `            }`,
      `            this.recolor(p, 1);`,
      `            if (wRight != null) {`,
      `                this.recolor(wRight, 1);`,
      `            }`,
      `            rotacionIzquierda(p);`,
      `        } else {`,
      `            // espejo: x es hijo derecho`,
      `            // Caso C: Hermano negro con cercano rojo (w.derecho), hijo lejano negro (w.izquierdo)`,
      `            if (wLeft == null || wLeft.color == 1) {`,
      `                if (wRight != null) {`,
      `                    this.recolor(wRight, 1);`,
      `                }`,
      `                if (w != null) {`,
      `                    this.recolor(w, 0);`,
      `                    this.rotacionIzquierda(w);`,
      `                }`,
      `                xParent = x != null ? x.padre : xParent;`,
      `                w = xParent.izquierdo;`,
      `            }`,
      `            // Caso D: Hermano negro con hijo lejano rojo`,
      `            if (w != null) {`,
      `                this.recolor(w, p != null ? p.color : 1);`,
      `            }`,
      `            this.recolor(p, 1);`,
      `            if (wLeft != null) {`,
      `                this.recolor(wLeft, 1);`,
      `            }`,
      `            rotacionDerecha(p);`,
      `        }`,
      `        x = this.raiz;`,
      `        xParent = null;`,
      `    }`,
      `    this.recolor(x, 1);`,
      `}`,
      `\n`,
      `\n`,
      `/**
 * Método auxiliar que sustituye el subárbol con raíz en u por el subárbol con raíz en v.
 * @param u Nodo raíz del subárbol a ser reemplazado.
 * @param v Nuevo nodo raíz del subárbol que ocupará la posición de u.
 */`,
      `private void transplantar(NodoRN<T> u, NodoRN<T> v) {`,
      `    NodoRN<T> up = u.padre;`,
      `    if (up == null) {`,
      `        this.raiz = v;`,
      `    } else if (u == up.izquierdo) {`,
      `        up.izquierdo = v;`,
      `    } else {`,
      `        up.derecho = v;`,
      `    }`,
      `    if (v != null) v.padre = up;`,
      `}`,
      `\n`,
      `\n`,
      `/**
 * Método auxiliar que modifica el color del nodo dado.
 * @param n Nodo cuyo color se va a modificar.
 * @param to Nuevo color del nodo.
 */`,
      `private void recolor(NodoRN<T> n, int to) {`,
      `    if (n == null) {`,
      `        return;`,
      `    }`,
      `    n.color = to;`,
      `}`,
      `\n`,
      `\n`,
      `/**
 * Método auxiliar que realiza una rotación simple a la derecha en el subárbol dado.
 * @param y Nodo raíz del subárbol a rotar.
 */`,
      `private void rotacionDerecha(NodoRN<T> y) {`,
      `    NodoRN<T> x = y.izquierdo;`,
      `    NodoRN<T> T2 = x.derecho;`,
      `\n`,
      `    x.padre = y.padre;`,
      `    if (y.padre == null) {`,
      `        this.raiz = x;`,
      `    } else if (y == y.padre.derecho) {`,
      `        y.padre.derecho = x;`,
      `    } else {`,
      `        y.padre.izquierdo = x;`,
      `    }`,
      `\n`,
      `    x.derecho = y;`,
      `    y.padre = x;`,
      `\n`,
      `    y.izquierdo = T2;`,
      `    if (T2 != null) {`,
      `        T2.padre = y;`,
      `    }`,
      `}`,
      `\n`,
      `\n`,
      `/**
 * Método auxiliar que realiza una rotación simple a la izquierda en el subárbol dado.
 * @param x Nodo raíz del subárbol a rotar.
 */`,
      `private void rotacionIzquierda(NodoRN<T> x) {`,
      `    NodoRN<T> y = x.derecho;`,
      `    NodoRN<T> T2 = y.izquierdo;`,
      `\n`,
      `    y.padre = x.padre;`,
      `    if (x.padre == null) {`,
      `        this.raiz = y;`,
      `    } else if (x == x.padre.izquierdo) {`,
      `        x.padre.izquierdo = y;`,
      `    } else {`,
      `        x.padre.derecho = y;`,
      `    }`,
      `\n`,
      `    y.izquierdo = x;`,
      `    x.padre = y;`,
      `\n`,
      `    x.derecho = T2;`,
      `    if (T2 != null) {`,
      `        T2.padre = x;`,
      `    }`,
      `}`,
    ],
    labels: {
      VALIDATE_EMPTY: 2,
      THROW_IF_EMPTY: 3,
      INIT_Z: 5,
      BST_WHILE: 6,
      DECLARE_CMP: 7,
      IF_MATCH_BREAK: 8,
      ADVANCE_Z: 9,
      IF_NOT_FOUND: 12,
      INIT_Y: 14,
      SAVE_Y_ORIGINAL_COLOR: 15,
      DECL_X: 17,
      DECL_XPARENT: 18,
      IF_NO_LEFT_CHILD: 20,
      SET_X_RIGHT: 21,
      SET_XPARENT_RIGHT: 22,
      TRANSPLANT_Z_RIGHT: 23,
      ELSE_IF_NO_RIGHT_CHILD: 24,
      SET_X_LEFT: 25,
      SET_XPARENT_LEFT: 26,
      TRANSPLANT_Z_LEFT: 27,
      ELSE_TWO_CHILDREN: 28,
      DECL_SUCC: 29,
      WHILE_SUCC_LEFT: 30,
      ADVANCE_SUCC_LEFT: 31,
      SET_Y_SUCC: 33,
      UPDATE_Y_ORIGINAL_COLOR: 34,
      SET_X_SUCC_RIGHT: 35,
      IF_SUCC_PARENT_IS_Z: 37,
      SET_XPARENT_DIRECT: 38,
      ELSE_SUCC_NOT_DIRECT: 39,
      TRANSPLANT_SUCC_WITH_RIGHT: 40,
      LINK_Y_RIGHT_TO_Z_RIGHT: 41,
      IF_Y_RIGHT_NOT_NULL: 42,
      SET_Y_RIGHT_PARENT: 43,
      SET_XPARENT_NOT_DIRECT: 45,
      TRANSPLANT_Z_WITH_Y: 47,
      LINK_Y_LEFT_TO_Z_LEFT: 48,
      IF_Y_LEFT_NOT_NULL: 49,
      SET_Y_LEFT_PARENT: 50,
      COPY_Z_COLOR_TO_Y: 52,
      IF_Y_ORIGINAL_BLACK_CALL_FIXUP: 55,
      CALL_DELETE_FIXUP: 56,
      DEC_SIZE: 58,
      RETURN_TRUE: 59,

      // deleteFixup(x, xParent)
      FIXUP_WHILE: 65,
      RESOLVE_P: 66,
      IF_P_NULL_BREAK: 67,
      DECL_X_IS_LEFT: 69,
      DECL_W: 70,

      // Caso 1
      IF_W_RED: 72,
      CASE1_RECOLOR_W_BLACK: 74,
      CASE1_RECOLOR_P_RED: 75,
      CASE1_IF_X_LEFT: 76,
      CASE1_ROTATE_LEFT_P: 77,
      CASE1_ELSE_X_RIGHT: 78,
      CASE1_ROTATE_RIGHT_P: 79,
      CASE1_UPDATE_XPARENT: 81,
      CASE1_UPDATE_W: 82,
      DECL_WLEFT: 85,
      DECL_WRIGHT: 86,

      // Caso 2
      IF_CASE2_W_CHILDREN_BLACK: 88,
      CASE2_IF_W_NOT_NULL: 90,
      CASE2_RECOLOR_W_RED: 91,
      CASE2_MOVE_X_UP: 93,
      CASE2_SET_XPARENT: 94,
      CASE2_CONTINUE: 95,

      // Casos 3/4
      IF_X_LEFT_BRANCH: 98,

      // Caso 3 (xEsIzq)
      CASE3_IF_WRIGHT_BLACK: 100,
      CASE3_IF_WLEFT_NOT_NULL: 101,
      CASE3_RECOLOR_WLEFT_BLACK: 102,
      CASE3_IF_W_NOT_NULL: 104,
      CASE3_RECOLOR_W_RED: 105,
      CASE3_ROTATE_RIGHT_W: 106,
      CASE3_UPDATE_XPARENT: 108,
      CASE3_UPDATE_W: 109,

      // Caso 4 (xEsIzq)
      CASE4_IF_W_NOT_NULL: 112,
      CASE4_RECOLOR_W_COLOR_OF_P: 113,
      CASE4_RECOLOR_P_BLACK: 115,
      CASE4_IF_WRIGHT_NOT_NULL: 116,
      CASE4_RECOLOR_WRIGHT_BLACK: 117,
      CASE4_ROTATE_LEFT_P: 119,

      // Espejo (x derecho)
      ELSE_MIRROR_BRANCH: 120,

      MIRROR_CASE3_IF_WLEFT_BLACK: 123,
      MIRROR_CASE3_IF_WRIGHT_NOT_NULL: 124,
      MIRROR_CASE3_RECOLOR_WRIGHT_BLACK: 125,
      MIRROR_CASE3_IF_W_NOT_NULL: 127,
      MIRROR_CASE3_RECOLOR_W_RED: 128,
      MIRROR_CASE3_ROTATE_LEFT_W: 129,
      MIRROR_CASE3_UPDATE_XPARENT: 131,
      MIRROR_CASE3_UPDATE_W: 132,

      MIRROR_CASE4_IF_W_NOT_NULL: 135,
      MIRROR_CASE4_RECOLOR_W_COLOR_OF_P: 136,
      MIRROR_CASE4_RECOLOR_P_BLACK: 138,
      MIRROR_CASE4_IF_WLEFT_NOT_NULL: 139,
      MIRROR_CASE4_RECOLOR_WLEFT_BLACK: 140,
      MIRROR_CASE4_ROTATE_RIGHT_P: 142,

      SET_X_ROOT: 144,
      SET_XPARENT_NULL: 145,
      FINAL_RECOLOR_X_BLACK: 147,

      // transplantar(u, v)
      TRANSPLANT_DECLARE_UP: 153,
      TRANSPLANT_IF_UP_NULL: 154,
      TRANSPLANT_SET_ROOT: 155,
      TRANSPLANT_ELSEIF_U_LEFT: 156,
      TRANSPLANT_SET_UP_LEFT: 157,
      TRANSPLANT_ELSE_U_RIGHT: 158,
      TRANSPLANT_SET_UP_RIGHT: 159,
      TRANSPLANT_SET_V_PARENT_UP: 161,

      // recolor(NodoRN<T> n, int to)
      VALIDATE_NULL_NODE: 167,
      RETURN_NULL_GUARD: 168,
      RECOLOR_ASSIGN: 170,

      // rotacionDerecha(NodoRN<T> y)
      ROT_RIGHT_DECL_X: 176,
      ROT_RIGHT_DECL_T2: 177,
      ROT_RIGHT_SET_X_PARENT: 179,
      ROT_RIGHT_IF_Y_PARENT_NULL: 180,
      ROT_RIGHT_SET_ROOT: 181,
      ROT_RIGHT_ELSE_IF_Y_RIGHT: 182,
      ROT_RIGHT_SET_Y_PARENT_RIGHT: 183,
      ROT_RIGHT_ELSE_Y_LEFT: 184,
      ROT_RIGHT_SET_Y_PARENT_LEFT: 185,
      ROT_RIGHT_SET_X_RIGHT: 188,
      ROT_RIGHT_SET_Y_PARENT: 189,
      ROT_RIGHT_SET_Y_LEFT: 191,
      ROT_RIGHT_IF_T2_NOT_NULL: 192,
      ROT_RIGHT_SET_T2_PARENT: 193,

      // rotacionIzquierda(NodoRN<T> x)
      ROT_LEFT_DECL_Y: 200,
      ROT_LEFT_DECL_T2: 201,
      ROT_LEFT_SET_Y_PARENT: 203,
      ROT_LEFT_IF_X_PARENT_NULL: 204,
      ROT_LEFT_SET_ROOT: 205,
      ROT_LEFT_ELSE_IF_X_LEFT: 206,
      ROT_LEFT_SET_X_PARENT_LEFT: 207,
      ROT_LEFT_ELSE_X_RIGHT: 208,
      ROT_LEFT_SET_X_PARENT_RIGHT: 209,
      ROT_LEFT_SET_Y_LEFT: 212,
      ROT_LEFT_SET_X_PARENT: 213,
      ROT_LEFT_SET_X_RIGHT: 215,
      ROT_LEFT_IF_T2_NOT_NULL: 216,
      ROT_LEFT_SET_T2_PARENT: 217
    },
    errorPlans: {
      DELETE_EMPTY: [
        { lineLabel: "VALIDATE_EMPTY", hold: 600 },
        { lineLabel: "THROW_IF_EMPTY", hold: 600 },
      ]
    }
  },
  search: {
    lines: [
      `/**
 * Método que comprueba la existencia del elemento especificado en el árbol Rojo-Negro.
 * @param info Elemento a buscar.
 * @return true si el elemento existe en el árbol, false en caso contrario.
 */`,
      `public boolean search(T {0}) {`,
      `    return this.search(this.raiz, {0});`,
      `}`,
      `\n`,
      `\n`,
      `/**
 * Método auxiliar que busca el nodo correspondiente al elemento proporcionado en el subárbol dado, 
 * aplicando las reglas del árbol binario de búsqueda.
 * @param r Nodo raíz del subárbol actual.
 * @param info Elemento a buscar.
 * @return true si el elemento existe en el subárbol, false en caso contrario.
 */`,
      `private boolean search(NodoRN<T> r, T {0}) {`,
      `    if (r == null) {`,
      `        return false;`,
      `    }`,
      `    int cmp = {0}.compareTo(r.info);`,
      `    if (cmp < 0) {`,
      `        return this.search(r.izquierdo, {0});`,
      `    } else if (cmp > 0) {`,
      `        return this.search(r.derecho, {0});`,
      `    } else {`,
      `        return true;`,
      `    }`,
      `}`,
    ],
    labels: {
      CALL_RECURSIVE_SEARCH: 2,

      // Método search(NodoRN<T> r, T info)
      IF_NULL_NODE: 8,
      RETURN_FALSE: 9,
      DECLARE_CMP: 11,
      IF_CMP_LT_ZERO: 12,
      CALL_LEFT_SUBTREE: 13,
      ELSE_IF_CMP_GT_ZERO: 14,
      CALL_RIGHT_SUBTREE: 15,
      ELSE_FOUND: 16,
      RETURN_TRUE: 17
    }
  },
  getInOrder: {
    lines: [
      `/**
 * Método que realiza el recorrido inorden del árbol Rojo-Negro.
 * @return Lista con la información de los nodos del árbol en secuencia inorden.
 */`,
      `public ListaCD<T> getInOrder() {`,
      `    ListaCD<T> nodos = new ListaCD<>();`,
      `    this.getInOrder(this.raiz, nodos);`,
      `    return nodos;`,
      `}`,
      `\n`,
      `\n`,
      `/**
 * Método auxiliar que realiza el recorrido inorden en el subárbol dado.
 * @param r Nodo raíz del subárbol actual.
 * @param nodos Lista donde se almacenan la información de los nodos visitados en secuencia inorden.
 */`,
      `private void getInOrder(NodoRN<T> r, ListaCD<T> nodos) {`,
      `    if (r == null) {`,
      `        return;`,
      `    }`,
      `    this.getInOrder(r.izquierdo, nodos);`,
      `    nodos.insertLast(r.info);`,
      `    this.getInOrder(r.derecho, nodos);`,
      `}`,
    ],
    labels: {
      DECLARE_LIST: 2,
      CALL_RECURSIVE_INORDER: 3,
      RETURN_LIST: 4,

      // Método getInOrder(NodoRN<T> r, ListaCD<T> nodos)
      IF_NULL_NODE: 10,
      RETURN_NULL: 11,
      CALL_LEFT: 13,
      VISIT_NODE: 14,
      CALL_RIGHT: 15
    }
  },
  getPreOrder: {
    lines: [
      `/**
 * Método que realiza el recorrido preorden del árbol Rojo-Negro.
 * @return Lista con la información de los nodos del árbol en secuencia preorden.
 */`,
      `public ListaCD<T> getPreOrder() {`,
      `    ListaCD<T> nodos = new ListaCD<>();`,
      `    this.getPreOrder(this.raiz, nodos);`,
      `    return nodos;`,
      `}`,
      `\n`,
      `\n`,
      `/**
 * Método auxiliar que realiza el recorrido preorden en el subárbol dado.
 * @param r Nodo raíz del subárbol actual.
 * @param nodos Lista donde se almacenan la información de los nodos visitados en secuencia preorden.
 */`,
      `private void getPreOrder(NodoRN<T> r, ListaCD<T> nodos) {`,
      `    if (r == null) {`,
      `        return;`,
      `    }`,
      `    nodos.insertLast(r.info);`,
      `    this.getPreOrder(r.izquierdo, nodos);`,
      `    this.getPreOrder(r.derecho, nodos);`,
      `}`,
    ],
    labels: {
      DECLARE_LIST: 2,
      CALL_RECURSIVE_INORDER: 3,
      RETURN_LIST: 4,

      // Método getPreOrder(NodoRN<T> r, ListaCD<T> nodos)
      IF_NULL_NODE: 10,
      RETURN_NULL: 11,
      VISIT_NODE: 13,
      CALL_LEFT: 14,
      CALL_RIGHT: 15
    }
  },
  getPostOrder: {
    lines: [
      `/**
 * Método que realiza el recorrido postorden del árbol Rojo-Negro.
 * @return Lista con la información de los nodos del árbol en secuencia postorden.
 */`,
      `public ListaCD<T> getPostOrder() {`,
      `    ListaCD<T> nodos = new ListaCD<>();`,
      `    this.getPostOrder(this.raiz, nodos);`,
      `    return nodos;`,
      `}`,
      `\n`,
      `\n`,
      `/**
 * Método auxiliar que realiza el recorrido postorden en el subárbol dado.
 * @param r Nodo raíz del subárbol actual.
 * @param nodos Lista donde se almacenan la información de los nodos visitados en secuencia postorden.
 */`,
      `private void getPostOrder(NodoRN<T> r, ListaCD<T> nodos) {`,
      `    if (r == null) {`,
      `        return;`,
      `    }`,
      `    this.getPostOrder(r.izquierdo, nodos);`,
      `    this.getPostOrder(r.derecho, nodos);`,
      `    nodos.insertLast(r.info);`,
      `}`,
    ],
    labels: {
      DECLARE_LIST: 2,
      CALL_RECURSIVE_INORDER: 3,
      RETURN_LIST: 4,

      // Método getPostOrder(NodoRN<T> r, ListaCD<T> nodos)
      IF_NULL_NODE: 10,
      RETURN_NULL: 11,
      CALL_LEFT: 13,
      CALL_RIGHT: 14,
      VISIT_NODE: 15,
    }
  },
  getLevelOrder: {
    lines: [
      `/**
 * Método que realiza el recorrido por niveles del árbol Rojo-Negro.
 * @return Lista con la información de los nodos del árbol por niveles.
 */`,
      `public ListaCD<T> getLevelOrder() {`,
      `    ListaCD<T> nodos = new ListaCD<>();`,
      `    if (this.raiz != null) {`,
      `        Cola<NodoRN<T>> cola = new Cola<>();`,
      `        cola.enqueue(this.raiz);`,
      `        \n`,
      `        while (!cola.isEmpty()) {`,
      `             NodoRN<T> nodo = cola.dequeue();`,
      `             nodos.insertLast(nodo.info);`,
      `             if (nodo.izquierdo != null) {`,
      `                 cola.enqueue(nodo.izquierdo);`,
      `             }`,
      `             if (nodo.derecho != null) {`,
      `                 cola.enqueue(nodo.derecho);`,
      `             }`,
      `        }`,
      `    }`,
      `    return nodos;`,
      `}`,
    ],
    labels: {
      DECLARE_LIST: 2,
      VALIDATE_EMPTY: 3,
      DECLARE_QUEUE: 4,
      ENQUEUE_ROOT: 5,
      WHILE_CHECK: 7,
      DEQUEUE_NODE: 8,
      VISIT_NODE: 9,
      IF_LEFT_NOT_NULL: 10,
      ENQUEUE_LEFT: 11,
      IF_RIGHT_NOT_NULL: 13,
      ENQUEUE_RIGHT: 14,
      RETURN_LIST: 18
    }
  },
  clean: {
    lines: [
      `/**
 * Método que elimina todos los nodos del árbol Rojo-Negro.
 */`,
      `public void clean() {`,
      `    this.raiz = null;`,
      `}`,
    ],
    labels: {
      CLEAR_ROOT: 2
    }
  }
});