export const data = [
    {
        title: 'Secuencia',
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/',
        toPracticar: '/',
    },
    {
        title: 'Lista Simplemente Enlazada',
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/',
        toPracticar: '/',
    },
    {
        title: 'Lista Doblemente Enlazada',
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/',
        toPracticar: '/',
    },
    {
        title: 'Lista Circular Simple',
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/',
        toPracticar: '/',
    },
    {
        title: 'Lista Circular Doble Enlazada',
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/',
        toPracticar: '/',
    },
    {
        title: 'Pila',
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/',
        toPracticar: '/',
    },
    {
        title: 'Cola',
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/',
        toPracticar: '/',
    },
    {
        title: 'Cola de Prioridad',
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/',
        toPracticar: '/',
    },
    {
        title: 'Tabla Hash',
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/',
        toPracticar: '/',
    },
    {
        title: 'Árbol Binario',
        img: '',
        bgCard: '#50ccf4',
        type: 'arbol_binario',
        bgButton: '#90def6',
        toConceptos: '/',
        toPracticar: '/',
    },
    {
        title: 'Árbol Binario de Búsqueda',
        img: '',
        bgCard: '#50ccf4',
        type: 'arbol_binario',
        bgButton: '#90def6',
        toConceptos: '/',
        toPracticar: '/',
    },
    {
        title: 'Árbol AVL',
        img: '',
        bgCard: '#50ccf4',
        type: 'arbol_binario',
        bgButton: '#90def6',
        toConceptos: '/',
        toPracticar: '/',
    },
    {
        title: 'Árbol RojiNegro',
        img: '',
        bgCard: '#50ccf4',
        type: 'arbol_binario',
        bgButton: '#90def6',
        toConceptos: '/',
        toPracticar: '/',
    },
    {
        title: 'Árbol Splay',
        img: '',
        bgCard: '#50ccf4',
        type: 'arbol_binario',
        bgButton: '#90def6',
        toConceptos: '/',
        toPracticar: '/',
    },
    {
        title: 'Árbol Heap',
        img: '',
        bgCard: '#50ccf4',
        type: 'arbol_binario',
        bgButton: '#90def6',
        toConceptos: '/',
        toPracticar: '/',
    },
    {
        title: 'Árbol Eneario',
        img: '',
        type: 'arbol_eneario',
        bgCard: '#ff5501',
        bgButton: '#ff9460',
        toConceptos: '',
        toPracticar: '',
    },
    {
        title: 'Árbol 1-2-3',
        img: '',
        type: 'arbol_eneario',
        bgCard: '#ff5501',
        bgButton: '#ff9460',
        toConceptos: '',
        toPracticar: '',
    },
    {
        title: 'Árbol B',
        img: '',
        type: 'arbol_eneario',
        bgCard: '#ff5501',
        bgButton: '#ff9460',
        toConceptos: '',
        toPracticar: '',
    },
    {
        title: 'Árbol B+',
        img: '',
        type: 'arbol_eneario',
        bgCard: '#ff5501',
        bgButton: '#ff9460',
        toConceptos: '',
        toPracticar: '',
    },
]