export const data = [
    {
        title: 'Secuencia',
        id: 1,
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/',
    },
    {
        title: 'Lista Simplemente Enlazada',
        id: 2,
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/',
    },
    {
        title: 'Lista Doblemente Enlazada',
        id: 3,
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/',
    },
    {
        title: 'Lista Circular Simple',
        id: 4,
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/',
    },
    {
        title: 'Lista Circular Doble Enlazada',
        id: 5,
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/',
    },
    {
        title: 'Pila',
        id: 6,
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/',
    },
    {
        title: 'Cola',
        id: 7,
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/',
    },
    {
        title: 'Cola de Prioridad',
        id: 8,
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/',
    },
    {
        title: 'Tabla Hash',
        id: 9,
        img: '',
        type: 'estructura_lineal',
        bgCard: '#7309b6',
        bgButton: '#b064d4',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/',
    },
    {
        title: 'Árbol Binario',
        id: 10,
        img: '',
        bgCard: '#50ccf4',
        type: 'arbol_binario',
        bgButton: '#90def6',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/',
    },
    {
        title: 'Árbol Binario de Búsqueda',
        id: 11,
        img: '',
        bgCard: '#50ccf4',
        type: 'arbol_binario',
        bgButton: '#90def6',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/',
    },
    {
        title: 'Árbol AVL',
        id: 12,
        img: '',
        bgCard: '#50ccf4',
        type: 'arbol_binario',
        bgButton: '#90def6',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/',
    },
    {
        title: 'Árbol RojiNegro',
        id: 13,
        img: '',
        bgCard: '#50ccf4',
        type: 'arbol_binario',
        bgButton: '#90def6',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/',
    },
    {
        title: 'Árbol Splay',
        id: 14,
        img: '',
        bgCard: '#50ccf4',
        type: 'arbol_binario',
        bgButton: '#90def6',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/',
    },
    {
        title: 'Árbol Heap',
        id: 15,
        img: '',
        bgCard: '#50ccf4',
        type: 'arbol_binario',
        bgButton: '#90def6',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/',
    },
    {
        title: 'Árbol Eneario',
        id: 16,
        img: '',
        type: 'arbol_eneario',
        bgCard: '#ff5501',
        bgButton: '#ff9460',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '',
    },
    {
        title: 'Árbol 1-2-3',
        id: 17,
        img: '',
        type: 'arbol_eneario',
        bgCard: '#ff5501',
        bgButton: '#ff9460',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '',
    },
    {
        title: 'Árbol B',
        id: 18,
        img: '',
        type: 'arbol_eneario',
        bgCard: '#ff5501',
        bgButton: '#ff9460',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '',
    },
    {
        title: 'Árbol B+',
        id: 19,
        img: '',
        type: 'arbol_eneario',
        bgCard: '#ff5501',
        bgButton: '#ff9460',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '',
    },
]