export const data = [
    {
        title: 'Secuencia',
        id: 1,
        img: '/assets/images/secuencia.png',
        type: 'estructura_lineal',
        bgCard: '#D02222',
        bgButton: '#E97F7F',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Lista Simplemente Enlazada',
        id: 2,
        img: '/assets/images/lista_simple.png',
        type: 'estructura_lineal',
        bgCard: '#D02222',
        bgButton: '#E97F7F',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Lista Doblemente Enlazada',
        id: 3,
        img: '/assets/images/lista_simple.png',
        type: 'estructura_lineal',
        bgCard: '#D02222',
        bgButton: '#E97F7F',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Lista Circular Simple',
        id: 4,
        img: '/assets/images/lista_simple.png',
        type: 'estructura_lineal',
        bgCard: '#D02222',
        bgButton: '#E97F7F',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Lista Circular Doblemente Enlazada',
        id: 5,
        img: '/assets/images/lista_simple.png',
        type: 'estructura_lineal',
        bgCard: '#D02222',
        bgButton: '#E97F7F',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Pila',
        id: 6,
        img: '/assets/images/pila.png',
        type: 'estructura_lineal',
        bgCard: '#D02222',
        bgButton: '#E97F7F',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Cola',
        id: 7,
        img: '/assets/images/cola.png',
        type: 'estructura_lineal',
        bgCard: '#D02222',
        bgButton: '#E97F7F',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Cola de Prioridad',
        id: 8,
        img: '/assets/images/cola.png',
        type: 'estructura_lineal',
        bgCard: '#D02222',
        bgButton: '#E97F7F',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Tabla Hash',
        id: 9,
        img: '/assets/images/tabla_hash.png',
        type: 'estructura_lineal',
        bgCard: '#D02222',
        bgButton: '#E97F7F',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Árbol Binario',
        id: 10,
        img: '/assets/images/arbol_binario.png',
        bgCard: '#669bbc',
        type: 'arbol_binario',
        bgButton: '#AEC5D3',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Árbol Binario de Búsqueda',
        id: 11,
        img: '/assets/images/arbol_binario.png',
        bgCard: '#669bbc',
        type: 'arbol_binario',
        bgButton: '#AEC5D3',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Árbol AVL',
        id: 12,
        img: '/assets/images/arbol_avl.jpg',
        bgCard: '#669bbc',
        type: 'arbol_binario',
        bgButton: '#AEC5D3',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Árbol RojiNegro',
        id: 13,
        img: '/assets/images/arbol_rn.png',
        bgCard: '#669bbc',
        type: 'arbol_binario',
        bgButton: '#AEC5D3',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Árbol Splay',
        id: 14,
        img: '/assets/images/arbol_splay.jpg',
        bgCard: '#669bbc',
        type: 'arbol_binario',
        bgButton: '#AEC5D3',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Árbol Heap',
        id: 15,
        img: '/assets/images/arbol_heap.jpg',
        bgCard: '#669bbc',
        type: 'arbol_binario',
        bgButton: '#AEC5D3',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Árbol Eneario',
        id: 16,
        img: '/assets/images/arbol_eneario.jpg',
        type: 'arbol_eneario',
        bgCard: '#A42121',
        bgButton: '#C46B6B',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Árbol 1-2-3',
        id: 17,
        img: '/assets/images/arbol_123.jpg',
        type: 'arbol_eneario',
        bgCard: '#A42121',
        bgButton: '#C46B6B',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Árbol B',
        id: 18,
        img: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi6uxV6yeyM6vLUspnMmz78vte7XykZ18ZIC99gbdU3Fe2cN9f0vkrDg98eAw6jMstRSR9IUS3wTykqnXmT2Z69NoThtbn2Jl-IIi4NOR0KFeJzZUuXw_-9rEqwg8BOin4ePTkfHPuPYE0/s1600/B13.jpg.jpg',
        type: 'arbol_eneario',
        bgCard: '#A42121',
        bgButton: '#C46B6B',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
    {
        title: 'Árbol B+',
        id: 19,
        img: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi6uxV6yeyM6vLUspnMmz78vte7XykZ18ZIC99gbdU3Fe2cN9f0vkrDg98eAw6jMstRSR9IUS3wTykqnXmT2Z69NoThtbn2Jl-IIi4NOR0KFeJzZUuXw_-9rEqwg8BOin4ePTkfHPuPYE0/s1600/B13.jpg.jpg',
        type: 'arbol_eneario',
        bgCard: '#A42121',
        bgButton: '#C46B6B',
        toConceptos: '/conceptos/$estructura',
        toPracticar: '/simulador/$estructura',
    },
]