/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SimuladorSecuenciaImport } from './routes/simulador/secuencia'
import { Route as SimuladorMemoriaImport } from './routes/simulador/memoria'
import { Route as ConceptosEstructuraImport } from './routes/conceptos/$estructura'
import { Route as ConceptosEstructuraOperacionesImport } from './routes/conceptos/$estructura/operaciones'
import { Route as ConceptosEstructuraDefinicionImport } from './routes/conceptos/$estructura/definicion'
import { Route as ConceptosEstructuraComplejidadImport } from './routes/conceptos/$estructura/complejidad'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SimuladorSecuenciaRoute = SimuladorSecuenciaImport.update({
  id: '/simulador/secuencia',
  path: '/simulador/secuencia',
  getParentRoute: () => rootRoute,
} as any)

const SimuladorMemoriaRoute = SimuladorMemoriaImport.update({
  id: '/simulador/memoria',
  path: '/simulador/memoria',
  getParentRoute: () => rootRoute,
} as any)

const ConceptosEstructuraRoute = ConceptosEstructuraImport.update({
  id: '/conceptos/$estructura',
  path: '/conceptos/$estructura',
  getParentRoute: () => rootRoute,
} as any)

const ConceptosEstructuraOperacionesRoute =
  ConceptosEstructuraOperacionesImport.update({
    id: '/operaciones',
    path: '/operaciones',
    getParentRoute: () => ConceptosEstructuraRoute,
  } as any)

const ConceptosEstructuraDefinicionRoute =
  ConceptosEstructuraDefinicionImport.update({
    id: '/definicion',
    path: '/definicion',
    getParentRoute: () => ConceptosEstructuraRoute,
  } as any)

const ConceptosEstructuraComplejidadRoute =
  ConceptosEstructuraComplejidadImport.update({
    id: '/complejidad',
    path: '/complejidad',
    getParentRoute: () => ConceptosEstructuraRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/conceptos/$estructura': {
      id: '/conceptos/$estructura'
      path: '/conceptos/$estructura'
      fullPath: '/conceptos/$estructura'
      preLoaderRoute: typeof ConceptosEstructuraImport
      parentRoute: typeof rootRoute
    }
    '/simulador/memoria': {
      id: '/simulador/memoria'
      path: '/simulador/memoria'
      fullPath: '/simulador/memoria'
      preLoaderRoute: typeof SimuladorMemoriaImport
      parentRoute: typeof rootRoute
    }
    '/simulador/secuencia': {
      id: '/simulador/secuencia'
      path: '/simulador/secuencia'
      fullPath: '/simulador/secuencia'
      preLoaderRoute: typeof SimuladorSecuenciaImport
      parentRoute: typeof rootRoute
    }
    '/conceptos/$estructura/complejidad': {
      id: '/conceptos/$estructura/complejidad'
      path: '/complejidad'
      fullPath: '/conceptos/$estructura/complejidad'
      preLoaderRoute: typeof ConceptosEstructuraComplejidadImport
      parentRoute: typeof ConceptosEstructuraImport
    }
    '/conceptos/$estructura/definicion': {
      id: '/conceptos/$estructura/definicion'
      path: '/definicion'
      fullPath: '/conceptos/$estructura/definicion'
      preLoaderRoute: typeof ConceptosEstructuraDefinicionImport
      parentRoute: typeof ConceptosEstructuraImport
    }
    '/conceptos/$estructura/operaciones': {
      id: '/conceptos/$estructura/operaciones'
      path: '/operaciones'
      fullPath: '/conceptos/$estructura/operaciones'
      preLoaderRoute: typeof ConceptosEstructuraOperacionesImport
      parentRoute: typeof ConceptosEstructuraImport
    }
  }
}

// Create and export the route tree

interface ConceptosEstructuraRouteChildren {
  ConceptosEstructuraComplejidadRoute: typeof ConceptosEstructuraComplejidadRoute
  ConceptosEstructuraDefinicionRoute: typeof ConceptosEstructuraDefinicionRoute
  ConceptosEstructuraOperacionesRoute: typeof ConceptosEstructuraOperacionesRoute
}

const ConceptosEstructuraRouteChildren: ConceptosEstructuraRouteChildren = {
  ConceptosEstructuraComplejidadRoute: ConceptosEstructuraComplejidadRoute,
  ConceptosEstructuraDefinicionRoute: ConceptosEstructuraDefinicionRoute,
  ConceptosEstructuraOperacionesRoute: ConceptosEstructuraOperacionesRoute,
}

const ConceptosEstructuraRouteWithChildren =
  ConceptosEstructuraRoute._addFileChildren(ConceptosEstructuraRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conceptos/$estructura': typeof ConceptosEstructuraRouteWithChildren
  '/simulador/memoria': typeof SimuladorMemoriaRoute
  '/simulador/secuencia': typeof SimuladorSecuenciaRoute
  '/conceptos/$estructura/complejidad': typeof ConceptosEstructuraComplejidadRoute
  '/conceptos/$estructura/definicion': typeof ConceptosEstructuraDefinicionRoute
  '/conceptos/$estructura/operaciones': typeof ConceptosEstructuraOperacionesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conceptos/$estructura': typeof ConceptosEstructuraRouteWithChildren
  '/simulador/memoria': typeof SimuladorMemoriaRoute
  '/simulador/secuencia': typeof SimuladorSecuenciaRoute
  '/conceptos/$estructura/complejidad': typeof ConceptosEstructuraComplejidadRoute
  '/conceptos/$estructura/definicion': typeof ConceptosEstructuraDefinicionRoute
  '/conceptos/$estructura/operaciones': typeof ConceptosEstructuraOperacionesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/conceptos/$estructura': typeof ConceptosEstructuraRouteWithChildren
  '/simulador/memoria': typeof SimuladorMemoriaRoute
  '/simulador/secuencia': typeof SimuladorSecuenciaRoute
  '/conceptos/$estructura/complejidad': typeof ConceptosEstructuraComplejidadRoute
  '/conceptos/$estructura/definicion': typeof ConceptosEstructuraDefinicionRoute
  '/conceptos/$estructura/operaciones': typeof ConceptosEstructuraOperacionesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conceptos/$estructura'
    | '/simulador/memoria'
    | '/simulador/secuencia'
    | '/conceptos/$estructura/complejidad'
    | '/conceptos/$estructura/definicion'
    | '/conceptos/$estructura/operaciones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conceptos/$estructura'
    | '/simulador/memoria'
    | '/simulador/secuencia'
    | '/conceptos/$estructura/complejidad'
    | '/conceptos/$estructura/definicion'
    | '/conceptos/$estructura/operaciones'
  id:
    | '__root__'
    | '/'
    | '/conceptos/$estructura'
    | '/simulador/memoria'
    | '/simulador/secuencia'
    | '/conceptos/$estructura/complejidad'
    | '/conceptos/$estructura/definicion'
    | '/conceptos/$estructura/operaciones'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConceptosEstructuraRoute: typeof ConceptosEstructuraRouteWithChildren
  SimuladorMemoriaRoute: typeof SimuladorMemoriaRoute
  SimuladorSecuenciaRoute: typeof SimuladorSecuenciaRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConceptosEstructuraRoute: ConceptosEstructuraRouteWithChildren,
  SimuladorMemoriaRoute: SimuladorMemoriaRoute,
  SimuladorSecuenciaRoute: SimuladorSecuenciaRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/conceptos/$estructura",
        "/simulador/memoria",
        "/simulador/secuencia"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/conceptos/$estructura": {
      "filePath": "conceptos/$estructura.tsx",
      "children": [
        "/conceptos/$estructura/complejidad",
        "/conceptos/$estructura/definicion",
        "/conceptos/$estructura/operaciones"
      ]
    },
    "/simulador/memoria": {
      "filePath": "simulador/memoria.tsx"
    },
    "/simulador/secuencia": {
      "filePath": "simulador/secuencia.tsx"
    },
    "/conceptos/$estructura/complejidad": {
      "filePath": "conceptos/$estructura/complejidad.tsx",
      "parent": "/conceptos/$estructura"
    },
    "/conceptos/$estructura/definicion": {
      "filePath": "conceptos/$estructura/definicion.tsx",
      "parent": "/conceptos/$estructura"
    },
    "/conceptos/$estructura/operaciones": {
      "filePath": "conceptos/$estructura/operaciones.tsx",
      "parent": "/conceptos/$estructura"
    }
  }
}
ROUTE_MANIFEST_END */
